(()=>{
let activeAgendaFilter='ALL';
const q=id=>document.getElementById(id);
function techFor(id){return (team||[]).find(x=>String(x.id)===String(id))||null}
function cardId(card){return card?.querySelector?.('[data-concert-view]')?.dataset?.concertView||card?.querySelector?.('[data-concert-team]')?.dataset?.concertTeam||card?.dataset?.concertId||null}
function stampCards(){const container=q('concerts');if(!container)return;[...container.querySelectorAll(':scope > .item')].forEach(card=>{const id=cardId(card);if(id)card.dataset.concertId=String(id)})}
function concertForCard(card){const id=cardId(card);if(!id)return null;return (concerts||[]).find(c=>String(c.id)===String(id))||null}
function stateFor(c){if(c?.closed)return'closed';const end=new Date(c?.ends_at||c?.starts_at||0);return end<new Date()?'past':'future'}
function applyState(card,c){if(!card||!c)return;card.classList.remove('agenda-future','agenda-past','agenda-closed');card.classList.add(stateFor(c)==='closed'?'agenda-closed':stateFor(c)==='past'?'agenda-past':'agenda-future')}
function ensureStyles(){if(q('agendaHistoryStateStyle'))return;const s=document.createElement('style');s.id='agendaHistoryStateStyle';s.textContent=`#concerts>.item.agenda-future{border-left:5px solid #2ecc71!important;background:rgba(46,204,113,.10)!important}#concerts>.item.agenda-past{border-left:5px solid #f1c40f!important;background:rgba(241,196,15,.11)!important}#concerts>.item.agenda-closed{border-left:5px solid #e74c3c!important;background:rgba(231,76,60,.11)!important}`;document.head.appendChild(s)}
function matches(c){if(!c)return false;const pos=String(c.work_position||'').trim().toUpperCase();if(activeAgendaFilter==='ALL')return true;if(activeAgendaFilter==='FOH')return pos==='FOH'||pos==='FOH+ROH';if(activeAgendaFilter==='ROH')return pos==='ROH'||pos==='FOH+ROH';if(activeAgendaFilter==='SUB')return !!c.substitute_technician_id||techFor(c.technician_id)?.role==='substitute';return true}
function applyAgendaFilter(){ensureStyles();stampCards();const container=q('concerts');if(!container)return;const cards=[...container.querySelectorAll(':scope > .item')];let visible=0;cards.forEach(card=>{const c=concertForCard(card);applyState(card,c);const filterOK=!!c&&matches(c);card.dataset.filterHidden=filterOK?'0':'1';const memberOK=card.dataset.memberHidden!=='1';const show=filterOK&&memberOK;card.style.setProperty('display',show?'':'none','important');if(show)visible++});let empty=q('agendaFilterEmpty');if(!empty){empty=document.createElement('div');empty.id='agendaFilterEmpty';empty.className='empty';container.insertAdjacentElement('afterend',empty)}empty.style.display=visible===0?'':'none';empty.textContent=activeAgendaFilter==='FOH'?'Sem datas FOH.':activeAgendaFilter==='ROH'?'Sem datas ROH.':activeAgendaFilter==='SUB'?'Sem datas atribuídas a substitutos.':'Sem trabalhos.';const title=document.querySelector('#agenda .title-row h2');if(title)title.textContent=activeAgendaFilter==='ALL'?'Agenda':activeAgendaFilter==='SUB'?'Agenda · Substitutos':`Agenda · ${activeAgendaFilter}`}
function setFilter(value,button){activeAgendaFilter=value;window.TeamDuckAgendaMembers?.reset?.();document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b===button));[0,50,180,500,1000].forEach(ms=>setTimeout(applyAgendaFilter,ms))}
function wire(){const agendaBtn=document.querySelector('#nav button[data-page="agenda"]:not([data-agenda-filter])'),fohBtn=document.querySelector('#nav button[data-agenda-filter="FOH"]'),rohBtn=document.querySelector('#nav button[data-agenda-filter="ROH"]'),subBtn=document.querySelector('#nav button[data-agenda-filter="SUB"]');[[agendaBtn,'ALL'],[fohBtn,'FOH'],[rohBtn,'ROH'],[subBtn,'SUB']].forEach(([b,v])=>{if(b&&!b.dataset.filterWired){b.dataset.filterWired='1';b.addEventListener('click',()=>setFilter(v,b))}})}
function observe(){const host=q('concerts');if(!host||window.__agendaFilterObserver)return;new MutationObserver(()=>setTimeout(applyAgendaFilter,0)).observe(host,{childList:true,subtree:true});window.__agendaFilterObserver=true}
function init(){wire();observe();setTimeout(applyAgendaFilter,100)}
if(document.readyState==='loading')addEventListener('load',init,{once:true});else init();
window.TeamDuckAgendaFilter={refresh:applyAgendaFilter,current:()=>activeAgendaFilter};
})();