(()=>{
const q=id=>document.getElementById(id);let selected='ALL',subMode=false,renderToken=0;const photoCache=new Map();
function activePeople(){return (team||[]).filter(p=>p.active!==false)}
function concertForCard(card,index){const id=card?.querySelector?.('[data-concert-view]')?.dataset?.concertView||card?.dataset?.concertId;if(id){const found=(concerts||[]).find(c=>String(c.id)===String(id));if(found)return found}return (concerts||[])[index]||null}
async function photoFor(p){if(!p?.photo_path)return '/401FB0DA-DAD2-49CE-89E0-A9850A0722F7.png';if(photoCache.has(p.photo_path))return photoCache.get(p.photo_path);try{const fn=window.TeamDuckImages?.signed;if(typeof fn==='function'){const u=await fn(p.photo_path);photoCache.set(p.photo_path,u);return u}const r=await sb.storage.from('team-images').createSignedUrl(p.photo_path,3600);const u=r.error?'/401FB0DA-DAD2-49CE-89E0-A9850A0722F7.png':r.data.signedUrl;photoCache.set(p.photo_path,u);return u}catch(_){return '/401FB0DA-DAD2-49CE-89E0-A9850A0722F7.png'}}
function cleanDuplicatePhotos(host){host?.querySelectorAll('[data-agenda-member]').forEach(btn=>{const primary=btn.querySelector('.td-member-single-photo');btn.querySelectorAll('img').forEach(img=>{if(img!==primary)img.remove()})})}
async function renderTabs(){const host=q('agendaMembers');if(!host)return;const token=++renderToken,people=activePeople();host.classList.toggle('td-substitute-directory',subMode);host.classList.toggle('td-member-tabs',!subMode);host.innerHTML=`<button type="button" class="secondary tiny td-general-member ${selected==='ALL'?'active':''}" data-agenda-member="ALL">Geral</button>`+people.map(p=>`<button type="button" class="secondary tiny td-member-tab ${subMode?'td-substitute-row':''} ${selected===String(p.id)?'active':''}" data-agenda-member="${p.id}" data-person-id="${p.id}"><img class="td-member-single-photo" data-member-photo="${p.id}" alt="${esc(p.full_name||'Técnico')}"><span class="td-member-copy"><b>${esc(p.full_name||p.email||'Membro')}</b>${subMode?`<small>${esc(p.base_city||'Cidade base por definir')}</small>`:''}</span></button>`).join('');cleanDuplicatePhotos(host);host.querySelectorAll('[data-agenda-member]').forEach(b=>b.onclick=e=>{if(e.target.closest('[data-member-photo]'))return;selected=b.dataset.agendaMember;renderTabs();apply()});for(const p of people){const img=host.querySelector(`img[data-member-photo="${p.id}"]`);if(!img)continue;img.src=await photoFor(p);img.onclick=e=>{e.stopPropagation();window.TeamDuckImages?.showPersonPhoto?.(p)}}cleanDuplicatePhotos(host);if(token!==renderToken)return}
function belongsTo(c,id){if(!c)return false;const ids=[c.principal_technician_id,c.technician_id,c.owner_id,c.substitute_technician_id].filter(Boolean).map(String);return ids.includes(String(id))}
function apply(){const host=q('concerts');if(!host)return;const cards=[...host.querySelectorAll(':scope > .item')];cards.forEach((card,i)=>{const c=concertForCard(card,i);if(c)card.dataset.concertId=c.id;if(!c)return;const byMember=selected==='ALL'||belongsTo(c,selected);card.dataset.memberHidden=byMember?'0':'1';const filterOK=card.dataset.filterHidden!=='1';card.style.display=(byMember&&filterOK)?'':'none'});const title=document.querySelector('#agenda .title-row h2');if(title){const p=activePeople().find(x=>String(x.id)===selected);title.textContent=selected==='ALL'?(subMode?'Agenda · Substitutos':'Agenda'):`Agenda · ${p?.full_name||'Membro'}`}}
function resetToGeneral(mode=subMode){subMode=!!mode;selected='ALL';renderTabs();setTimeout(apply,0)}
function hookAgendaClick(){document.querySelectorAll('#nav button[data-page="agenda"]').forEach(btn=>{if(btn.dataset.memberModeWired)return;btn.dataset.memberModeWired='1';btn.addEventListener('click',()=>resetToGeneral(btn.dataset.agendaFilter==='SUB'))})}
function patchLoadAll(){if(window.__agendaMembersPatched||typeof window.loadAll!=='function')return;const old=window.loadAll;window.loadAll=async function(...args){const r=await old.apply(this,args);renderTabs();setTimeout(apply,0);return r};window.__agendaMembersPatched=true}
function init(){hookAgendaClick();patchLoadAll();setTimeout(()=>{renderTabs();apply()},150);setTimeout(()=>{renderTabs();apply()},700);const css=document.createElement('style');css.textContent=`#agendaMembers.td-member-tabs{display:flex;gap:7px;overflow:auto;flex-wrap:nowrap}#agendaMembers .td-member-tab{display:inline-flex!important;align-items:center!important;gap:7px!important}#agendaMembers .td-member-single-photo{width:28px;height:28px;border-radius:50%;object-fit:cover;flex:0 0 28px;border:1px solid rgba(255,255,255,.18);background:#0b2b19;cursor:pointer}#agendaMembers .td-member-copy{display:flex;align-items:center;gap:4px}#agendaMembers .td-member-copy b{font-size:inherit}#agendaMembers.td-substitute-directory{display:flex!important;flex-direction:column!important;align-items:stretch!important;gap:8px!important;max-height:52vh;overflow-y:auto!important;overflow-x:hidden!important;padding:2px 2px 6px!important}#agendaMembers.td-substitute-directory .td-general-member{width:100%;justify-content:flex-start}#agendaMembers .td-substitute-row{width:100%!important;display:grid!important;grid-template-columns:50px minmax(0,1fr)!important;align-items:center!important;text-align:left!important;padding:10px 12px!important;min-height:64px!important}#agendaMembers .td-substitute-row .td-member-single-photo{width:44px;height:44px;flex-basis:44px}#agendaMembers .td-substitute-row .td-member-copy{display:grid;gap:2px;min-width:0}#agendaMembers .td-substitute-row .td-member-copy b{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}#agendaMembers .td-substitute-row .td-member-copy small{font-size:12px;opacity:.72;font-weight:600}#agendaMembers .td-substitute-row img:not(.td-member-single-photo){display:none!important}@media(max-width:600px){#agendaMembers.td-substitute-directory{max-height:48vh}#agendaMembers .td-substitute-row{min-height:60px;padding:8px 10px}}`;document.head.appendChild(css)}
if(document.readyState==='loading')addEventListener('load',init,{once:true});else init();
window.TeamDuckAgendaMembers={apply,reset:()=>resetToGeneral(false),current:()=>selected,refresh:renderTabs,setSubstituteMode:v=>resetToGeneral(!!v)};
})();
