(()=>{
const q=id=>document.getElementById(id);let selected='ALL',renderToken=0;const photoCache=new Map();
function activePeople(){return (team||[]).filter(p=>p.active!==false)}
function concertForCard(card,index){const id=card?.querySelector?.('[data-concert-view]')?.dataset?.concertView||card?.dataset?.concertId;if(id){const found=(concerts||[]).find(c=>String(c.id)===String(id));if(found)return found}return (concerts||[])[index]||null}
async function photoFor(p){if(!p?.photo_path)return '/401FB0DA-DAD2-49CE-89E0-A9850A0722F7.png';if(photoCache.has(p.photo_path))return photoCache.get(p.photo_path);try{const fn=window.TeamDuckImages?.signed;if(typeof fn==='function'){const u=await fn(p.photo_path);photoCache.set(p.photo_path,u);return u}const r=await sb.storage.from('team-images').createSignedUrl(p.photo_path,3600);const u=r.error?'/401FB0DA-DAD2-49CE-89E0-A9850A0722F7.png':r.data.signedUrl;photoCache.set(p.photo_path,u);return u}catch(_){return '/401FB0DA-DAD2-49CE-89E0-A9850A0722F7.png'}}
async function renderTabs(){const host=q('agendaMembers');if(!host)return;const token=++renderToken,people=activePeople();host.innerHTML=`<button type="button" class="secondary tiny ${selected==='ALL'?'active':''}" data-agenda-member="ALL">Geral</button>`+people.map(p=>`<button type="button" class="secondary tiny td-member-tab ${selected===String(p.id)?'active':''}" data-agenda-member="${p.id}"><span class="td-member-tab-photo" data-member-photo="${p.id}"></span><span>${esc(p.full_name||p.email||'Membro')}</span></button>`).join('');host.querySelectorAll('[data-agenda-member]').forEach(b=>b.onclick=e=>{if(e.target.closest('[data-member-photo]'))return;selected=b.dataset.agendaMember;renderTabs();apply()});for(const p of people){const slot=host.querySelector(`[data-member-photo="${p.id}"]`);if(!slot)continue;const img=document.createElement('img');img.alt=p.full_name||'Técnico';img.src=await photoFor(p);img.loading='lazy';img.onclick=e=>{e.stopPropagation();window.TeamDuckImages?.showPersonPhoto?.(p)};slot.appendChild(img)}if(token!==renderToken)return}
function belongsTo(c,id){if(!c)return false;const ids=[c.principal_technician_id,c.technician_id,c.owner_id,c.substitute_technician_id].filter(Boolean).map(String);return ids.includes(String(id))}
function apply(){const host=q('concerts');if(!host)return;const cards=[...host.querySelectorAll(':scope > .item')];cards.forEach((card,i)=>{const c=concertForCard(card,i);if(c)card.dataset.concertId=c.id;if(!c)return;const byMember=selected==='ALL'||belongsTo(c,selected);card.dataset.memberHidden=byMember?'0':'1';const filterOK=card.dataset.filterHidden!=='1';card.style.display=(byMember&&filterOK)?'':'none'});const title=document.querySelector('#agenda .title-row h2');if(title){const p=activePeople().find(x=>String(x.id)===selected);title.textContent=selected==='ALL'?'Agenda':`Agenda · ${p?.full_name||'Membro'}`}}
function resetToGeneral(){selected='ALL';renderTabs();setTimeout(apply,0)}
function hookAgendaClick(){document.querySelectorAll('#nav button[data-page="agenda"]').forEach(btn=>btn.addEventListener('click',resetToGeneral))}
function patchLoadAll(){if(window.__agendaMembersPatched||typeof window.loadAll!=='function')return;const old=window.loadAll;window.loadAll=async function(...args){const r=await old.apply(this,args);renderTabs();setTimeout(apply,0);return r};window.__agendaMembersPatched=true}
function init(){hookAgendaClick();patchLoadAll();setTimeout(()=>{renderTabs();apply()},150);setTimeout(()=>{renderTabs();apply()},700);const css=document.createElement('style');css.textContent='.td-member-tab{display:inline-flex!important;align-items:center!important;gap:7px!important}.td-member-tab-photo{display:inline-flex;width:28px;height:28px;border-radius:50%;overflow:hidden;flex:0 0 28px;border:1px solid rgba(255,255,255,.18);background:#0b2b19}.td-member-tab-photo img{width:100%;height:100%;object-fit:cover;cursor:pointer;display:block}.td-member-tab-photo img:hover{filter:brightness(1.08)}';document.head.appendChild(css)}
if(document.readyState==='loading')addEventListener('load',init,{once:true});else init();
window.TeamDuckAgendaMembers={apply,reset:resetToGeneral,current:()=>selected,refresh:renderTabs};
})();
