const SUPABASE_URL='https://fnuchugrbwvmmtfbpboa.supabase.co';
const SUPABASE_KEY='sb_publishable_6onPy_AryFOeIp5XGgwcQA_OrgCijmm';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storage:window.localStorage,storageKey:'team-duck-v5-auth'}});
const $=id=>document.getElementById(id);let artists=[],concerts=[],team=[],invites=[],files=[],me=null,currentArtist=null,appVisible=false;
const MAX_LOGICAL_FILE=500*1024*1024,PART_SIZE=20*1024*1024;
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const money=v=>new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format(Number(v||0));
const dt=v=>v?new Intl.DateTimeFormat('pt-PT',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'';
const roleLabel=r=>({admin:'Administrador',partner:'Parceiro',substitute:'Substituto'})[r]||r||'Equipa';
const can=p=>me?.role==='admin'||me?.permissions?.[p]===true;
function toast(msg){const t=$('toast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3500)}
function showLogin(){$('inviteScreen').classList.add('hidden');$('login').classList.remove('hidden');$('app').classList.add('hidden');appVisible=false}
async function showApp(){if(appVisible)return;appVisible=true;$('inviteScreen').classList.add('hidden');$('login').classList.add('hidden');$('app').classList.remove('hidden');await loadAll()}
async function loadAll(){const {data:{user}}=await sb.auth.getUser();const [m,a,c,p]=await Promise.all([sb.from('profiles').select('*').eq('id',user.id).single(),sb.from('artists').select('*').order('name'),sb.from('concerts').select('*,artists(name)').order('starts_at'),sb.from('profiles').select('*').order('full_name')]);me=m.data;artists=a.data||[];concerts=c.data||[];team=p.data||[];if(can('team_manage')){const r=await sb.from('team_invitations').select('*').order('created_at',{ascending:false});invites=r.data||[]}else invites=[];render()}
function render(){const future=concerts.filter(c=>new Date(c.starts_at)>=new Date()&&!c.closed);$('whoami').textContent=`${me?.full_name||me?.email||'Sound Engineer Management'} · ${roleLabel(me?.role)}`;$('statConcerts').textContent=future.length;$('statArtists').textContent=artists.length;$('statDue').textContent=can('financials_view')?money(concerts.filter(c=>!c.closed).reduce((s,c)=>s+Math.max(0,Number(c.fee_override||0)-Number(c.amount_received||0)),0)):'—';const workCard=c=>`<article class="item"><div><strong>${esc(c.artists?.name||'Trabalho')}</strong><small>${dt(c.starts_at)} · ${esc(c.city||c.venue||'Local por definir')} · ${esc(c.work_position||'')}</small></div>${can('financials_view')?`<span class="money">${money(c.fee_override)}</span>`:''}</article>`;$('nextConcerts').innerHTML=future.slice(0,5).map(workCard).join('')||'<div class="empty">Sem trabalhos futuros.</div>';$('concerts').innerHTML=concerts.map(workCard).join('')||'<div class="empty">Sem trabalhos.</div>';$('artistList').innerHTML=artists.map(a=>`<article class="item"><div><strong>${esc(a.name)}</strong><small>${esc(a.contact_email||a.contact_phone||'Sem contacto')}</small></div><div class="file-actions">${can('financials_view')?`<span class="money">${money(a.base_fee)}</span>`:''}<button type="button" class="secondary tiny" data-artist-files="${a.id}">Ficheiros</button></div></article>`).join('')||'<div class="empty">Sem artistas.</div>';document.querySelectorAll('[data-artist-files]').forEach(b=>b.onclick=()=>openArtistFiles(b.dataset.artistFiles));$('teamList').innerHTML=team.map(p=>`<article class="item ${can('team_manage')?'clickable':''}" data-member="${p.id}"><div><strong>${esc(p.full_name||p.email||'Membro')}</strong><small>${esc(p.email||'')} · ${roleLabel(p.role)} · ${p.active?'ativo':'inativo'}</small></div></article>`).join('')||'<div class="empty">Sem membros.</div>';if(can('team_manage'))document.querySelectorAll('[data-member]').forEach(x=>x.onclick=()=>openMember(x.dataset.member));$('inviteList').innerHTML=can('team_manage')?(invites.map(i=>`<article class="item"><div><strong>${esc(i.email)}</strong><small>${roleLabel(i.role)} · ${i.accepted_at?'aceite':i.revoked_at?'revogado':new Date(i.expires_at)<new Date()?'expirado':'pendente'}</small></div></article>`).join('')||'<div class="empty">Sem convites.</div>'):'<div class="empty">Só administradores podem gerir convites.</div>';$('newMember').classList.toggle('hidden',!can('team_manage'));$('newArtist').classList.toggle('hidden',!can('artists_manage'));$('newConcert').classList.toggle('hidden',!can('concerts_manage'));$('concertArtist').innerHTML='<option value="">Selecionar</option>'+artists.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('')}
async function openArtistFiles(id){currentArtist=artists.find(a=>a.id===id);if(!currentArtist)return;$('artistFilesTitle').textContent='Ficheiros · '+currentArtist.name;$('artistFilesDialog').showModal();await loadArtistFiles()}
async function loadArtistFiles(){const r=await sb.from('artist_files').select('*').eq('artist_id',currentArtist.id).order('created_at',{ascending:false});files=r.data||[];$('artistFiles').innerHTML=files.map(f=>`<article class="item"><div><strong>${esc(f.file_name)}</strong><small>${esc(f.category)} · ${Math.round((f.size_bytes||0)/1048576)} MB${Array.isArray(f.chunks)&&f.chunks.length>1?' · ficheiro grande':''}</small></div><div class="file-actions"><button type="button" class="secondary tiny" data-openfile="${f.id}">Abrir</button>${can('files_manage')?`<button type="button" class="danger tiny" data-deletefile="${f.id}">Apagar</button>`:''}</div></article>`).join('')||'<div class="empty">Sem ficheiros.</div>';document.querySelectorAll('[data-openfile]').forEach(b=>b.onclick=()=>openFile(b.dataset.openfile));document.querySelectorAll('[data-deletefile]').forEach(b=>b.onclick=()=>deleteFile(b.dataset.deletefile))}
function fileParts(f){return Array.isArray(f.chunks)&&f.chunks.length?f.chunks:(f.storage_path?[f.storage_path]:[])}
async function openFile(id){const f=files.find(x=>x.id===id);if(!f)return;const parts=fileParts(f);if(!parts.length)return toast('Ficheiro sem dados.');const popup=window.open('about:blank','_blank');$('uploadProgress').classList.remove('hidden');$('uploadBar').style.width='0%';$('uploadText').textContent='A preparar ficheiro…';try{const blobs=[];for(let i=0;i<parts.length;i++){const s=await sb.storage.from('artist-files').createSignedUrl(parts[i],3600);if(s.error)throw s.error;const resp=await fetch(s.data.signedUrl);if(!resp.ok)throw new Error('Não foi possível ler uma parte do ficheiro.');blobs.push(await resp.blob());const pct=Math.round(((i+1)/parts.length)*100);$('uploadBar').style.width=pct+'%';$('uploadText').textContent=`A preparar ficheiro… ${pct}%`}const blob=new Blob(blobs,{type:f.mime_type||'application/octet-stream'}),url=URL.createObjectURL(blob);$('uploadProgress').classList.add('hidden');if(popup)popup.location.href=url;else{const a=document.createElement('a');a.href=url;a.target='_blank';a.download=f.file_name;document.body.appendChild(a);a.click();a.remove()}setTimeout(()=>URL.revokeObjectURL(url),10*60*1000)}catch(err){console.error(err);$('uploadProgress').classList.add('hidden');if(popup)popup.close();toast('Não foi possível abrir o ficheiro.') }}
async function deleteFile(id){const f=files.find(x=>x.id===id);if(!f||!confirm('Apagar '+f.file_name+'?'))return;const parts=fileParts(f);if(parts.length){const r=await sb.storage.from('artist-files').remove(parts);if(r.error)return toast(r.error.message)}await sb.from('artist_files').delete().eq('id',id);toast('Ficheiro apagado');await loadArtistFiles()}
async function uploadLargeFile(file,category){if(file.size>MAX_LOGICAL_FILE)throw new Error('Limite máximo: 500 MB.');const safe=file.name.replace(/[^A-Za-z0-9_.()'!*,&$@=;:+? -]/g,'_'),uploadId=crypto.randomUUID(),totalParts=Math.ceil(file.size/PART_SIZE),paths=[];try{for(let i=0;i<totalParts;i++){const start=i*PART_SIZE,end=Math.min(file.size,start+PART_SIZE),blob=file.slice(start,end),partPath=`${currentArtist.id}/${category}/${uploadId}/part-${String(i+1).padStart(3,'0')}-${safe}`;const r=await sb.storage.from('artist-files').upload(partPath,blob,{contentType:'application/octet-stream',cacheControl:'3600',upsert:false});if(r.error)throw r.error;paths.push(partPath);const pct=Math.round((end/file.size)*100);$('uploadBar').style.width=pct+'%';$('uploadText').textContent=`${pct}% · ${Math.round(end/1048576)} de ${Math.round(file.size/1048576)} MB`}return paths}catch(err){if(paths.length)await sb.storage.from('artist-files').remove(paths);throw err}}
$('artistFilePicker').onchange=async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(!can('files_manage'))return toast('Sem permissão para carregar ficheiros.');if(file.size>MAX_LOGICAL_FILE)return toast('Limite máximo: 500 MB por ficheiro.');const category=$('artistFileCategory').value;$('uploadProgress').classList.remove('hidden');$('uploadBar').style.width='0%';$('uploadText').textContent='A preparar upload…';try{const paths=await uploadLargeFile(file,category);const {data:{user}}=await sb.auth.getUser();const r=await sb.from('artist_files').insert({artist_id:currentArtist.id,file_name:file.name,storage_path:paths[0],chunks:paths,mime_type:file.type||'application/octet-stream',size_bytes:file.size,category,uploaded_by:user.id});if(r.error){await sb.storage.from('artist-files').remove(paths);throw r.error}$('uploadProgress').classList.add('hidden');toast('Ficheiro carregado');await loadArtistFiles()}catch(err){console.error(err);$('uploadProgress').classList.add('hidden');toast('Falha no upload: '+(err?.message||'erro desconhecido'))}};
function permissionDefaults(role){return role==='admin'?['artists_manage','files_manage','concerts_manage','financials_view','documents_manage','team_manage']:role==='partner'?['artists_manage','files_manage','concerts_manage','financials_view']:[]}
function setInviteDefaults(){const d=permissionDefaults($('inviteRole').value);document.querySelectorAll('[data-perm]').forEach(c=>c.checked=d.includes(c.dataset.perm))}
$('inviteRole').onchange=setInviteDefaults;setInviteDefaults();
$('newMember').onclick=()=>{$('inviteDialog').showModal();setInviteDefaults()};$('newArtist').onclick=()=>$('artistDialog').showModal();$('newConcert').onclick=()=>$('concertDialog').showModal();
$('inviteForm').onsubmit=async e=>{e.preventDefault();const permissions={};document.querySelectorAll('[data-perm]').forEach(c=>permissions[c.dataset.perm]=c.checked);const r=await sb.functions.invoke('create-team-invite',{body:{email:$('inviteMemberEmail').value.trim(),role:$('inviteRole').value,permissions}});if(r.error||!r.data?.ok)return toast(r.data?.error||r.error?.message||'Erro ao criar convite');const link=`${location.origin}${location.pathname}?invite=${encodeURIComponent(r.data.invitation.token)}`;$('inviteDialog').close();$('inviteLink').value=link;$('inviteLinkDialog').showModal();e.target.reset();setInviteDefaults();await loadAll()};
$('copyInvite').onclick=async()=>{await navigator.clipboard.writeText($('inviteLink').value);toast('Link copiado')};$('shareInvite').onclick=async()=>{const url=$('inviteLink').value;if(navigator.share)await navigator.share({title:'Convite Team Duck',text:'Cria as tuas credenciais Team Duck neste link:',url});else{await navigator.clipboard.writeText(url);toast('Link copiado')}};
function openMember(id){const p=team.find(x=>x.id===id);if(!p)return;$('memberId').value=p.id;$('memberName').value=p.full_name||'';$('memberPhone').value=p.phone||'';$('memberNif').value=p.nif||'';$('memberIdNumber').value=p.identification_number||'';$('memberRole').value=p.role;$('memberActive').checked=!!p.active;document.querySelectorAll('[data-member-perm]').forEach(c=>c.checked=!!p.permissions?.[c.dataset.memberPerm]);$('memberDialog').showModal()}
$('memberForm').onsubmit=async e=>{e.preventDefault();const permissions={};document.querySelectorAll('[data-member-perm]').forEach(c=>permissions[c.dataset.memberPerm]=c.checked);const r=await sb.functions.invoke('update-team-member',{body:{id:$('memberId').value,full_name:$('memberName').value.trim(),phone:$('memberPhone').value.trim(),nif:$('memberNif').value.trim(),identification_number:$('memberIdNumber').value.trim(),role:$('memberRole').value,active:$('memberActive').checked,permissions}});if(r.error||!r.data?.ok)return toast(r.data?.error||r.error?.message||'Erro ao guardar');$('memberDialog').close();toast('Membro atualizado');await loadAll()};
$('artistForm').onsubmit=async e=>{e.preventDefault();if(!can('artists_manage'))return toast('Sem permissão.');const {data:{user}}=await sb.auth.getUser();const r=await sb.from('artists').insert({name:$('artistName').value.trim(),base_fee:$('artistFee').value||null,contact_phone:$('artistPhone').value||null,contact_email:$('artistEmail').value||null,notes:$('artistNotes').value||null,created_by:user.id});if(r.error)return toast(r.error.message);$('artistDialog').close();e.target.reset();toast('Artista guardado');await loadAll()};
$('concertForm').onsubmit=async e=>{e.preventDefault();if(!can('concerts_manage'))return toast('Sem permissão.');const {data:{user}}=await sb.auth.getUser();const r=await sb.from('concerts').insert({artist_id:$('concertArtist').value,starts_at:new Date($('concertStart').value).toISOString(),ends_at:$('concertEnd').value?new Date($('concertEnd').value).toISOString():null,venue:$('concertVenue').value||null,city:$('concertCity').value||null,work_position:$('concertPosition').value,fee_override:$('concertFee').value||null,amount_received:$('concertReceived').value||0,notes:$('concertNotes').value||null,status:'confirmed',created_by:user.id,owner_id:user.id});if(r.error)return toast(r.error.message);$('concertDialog').close();e.target.reset();toast('Trabalho guardado');await loadAll()};
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginError').textContent='';const b=e.submitter||$('loginForm').querySelector('button');b.disabled=true;b.textContent='A entrar…';try{const r=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(r.error||!r.data.session){$('loginError').textContent='E-mail ou password incorretos.';return}await showApp()}finally{b.disabled=false;b.textContent='Entrar'}};
$('logout').onclick=async()=>{await sb.auth.signOut({scope:'local'});localStorage.removeItem('team-duck-v5-auth');showLogin()};document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.page').forEach(p=>p.classList.toggle('hidden',p.id!==b.dataset.page))});document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
async function inviteBoot(token){$('login').classList.add('hidden');$('app').classList.add('hidden');$('inviteScreen').classList.remove('hidden');$('inviteAcceptForm').onsubmit=async e=>{e.preventDefault();$('inviteError').textContent='';if($('invitePassword').value!==$('invitePassword2').value){$('inviteError').textContent='As passwords não coincidem.';return}const r=await sb.functions.invoke('accept-team-invite',{body:{token,full_name:$('inviteFullName').value.trim(),phone:$('invitePhone').value.trim(),nif:$('inviteNif').value.trim(),identification_number:$('inviteIdNumber').value.trim(),password:$('invitePassword').value}});if(r.error||!r.data?.ok){$('inviteError').textContent=r.data?.error||r.error?.message||'Não foi possível aceitar o convite.';return}toast('Conta criada. Já podes iniciar sessão.');history.replaceState({},'',location.pathname);showLogin();$('email').value=r.data.email||''}};
(async function boot(){const token=new URLSearchParams(location.search).get('invite');if(token){await inviteBoot(token);return}const {data,error}=await sb.auth.getSession();if(error){localStorage.removeItem('team-duck-v5-auth');showLogin();return}if(data.session)await showApp();else showLogin();sb.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'||!session)showLogin()})})();