(()=>{
  const q=id=>document.getElementById(id);
  function ensureUI(){
    if(!q('artistEditDialog')) document.body.insertAdjacentHTML('beforeend',`<dialog id="artistEditDialog"><form id="artistEditForm"><h3>Editar artista</h3><input id="artistEditId" type="hidden"><label>Nome<input id="artistEditName" required></label><label>Cachet base (€)<input id="artistEditFee" type="number" step=".01"></label><label>Telefone<input id="artistEditPhone"></label><label>E-mail<input id="artistEditEmail" type="email"></label><hr><h4>Manager</h4><label>Nome do manager<input id="artistEditManager"></label><label>E-mail do manager<input id="artistEditManagerEmail" type="email"></label><label>Telefone do manager<input id="artistEditManagerPhone"></label><hr><h4>Faturação</h4><label>Nome de faturação<input id="artistEditBillingName"></label><label>NIF / Nº fiscal<input id="artistEditTax"></label><label>E-mail de faturação 1<input id="artistEditBillingEmail1" type="email"></label><label>E-mail de faturação 2<input id="artistEditBillingEmail2" type="email"></label><label>E-mail de faturação 3<input id="artistEditBillingEmail3" type="email"></label><label>Morada de faturação<textarea id="artistEditBillingAddress"></textarea></label><label>Notas<textarea id="artistEditNotes"></textarea></label><div class="actions"><button type="button" class="secondary" id="artistEditCancel">Cancelar</button><button type="submit">Guardar alterações</button></div></form></dialog>`);
    q('artistEditCancel')?.addEventListener('click',()=>q('artistEditDialog').close());
    if(q('artistForm')&&!q('artistExtraFields')){
      const actions=q('artistForm').querySelector('.actions');
      actions?.insertAdjacentHTML('beforebegin',`<div id="artistExtraFields"><hr><h4>Manager</h4><label>Nome do manager<input id="artistManagerName"></label><label>E-mail do manager<input id="artistManagerEmail" type="email"></label><label>Telefone do manager<input id="artistManagerPhone"></label><hr><h4>Faturação</h4><label>Nome de faturação<input id="artistBillingName"></label><label>NIF / Nº fiscal<input id="artistTaxNumber"></label><label>E-mail de faturação 1<input id="artistBillingEmail1" type="email"></label><label>E-mail de faturação 2<input id="artistBillingEmail2" type="email"></label><label>E-mail de faturação 3<input id="artistBillingEmail3" type="email"></label><label>Morada de faturação<textarea id="artistBillingAddress"></textarea></label></div>`);
    }
    if(q('memberForm')&&!q('memberEmail')){
      q('memberName')?.closest('label')?.insertAdjacentHTML('afterend','<label>E-mail<input id="memberEmail" type="email" required></label>');
    }
  }
  function openArtistEdit(id){
    const a=artists.find(x=>String(x.id)===String(id)); if(!a)return;
    if(!can('artists_manage'))return toast('Sem permissão para editar artistas.');
    q('artistEditId').value=a.id;q('artistEditName').value=a.name||'';q('artistEditFee').value=a.base_fee??'';q('artistEditPhone').value=a.contact_phone||'';q('artistEditEmail').value=a.contact_email||'';q('artistEditManager').value=a.manager_name||'';q('artistEditManagerEmail').value=a.manager_email||'';q('artistEditManagerPhone').value=a.manager_phone||'';q('artistEditTax').value=a.tax_number||'';q('artistEditBillingName').value=a.billing_name||'';q('artistEditBillingEmail1').value=a.billing_email||'';q('artistEditBillingEmail2').value=a.billing_email_2||'';q('artistEditBillingEmail3').value=a.billing_email_3||'';q('artistEditBillingAddress').value=a.billing_address||'';q('artistEditNotes').value=a.notes||'';q('artistEditDialog').showModal();
  }
  async function saveArtist(e){
    e.preventDefault(); const id=q('artistEditId').value;
    const patch={name:q('artistEditName').value.trim(),base_fee:q('artistEditFee').value||null,contact_phone:q('artistEditPhone').value.trim()||null,contact_email:q('artistEditEmail').value.trim()||null,manager_name:q('artistEditManager').value.trim()||null,manager_email:q('artistEditManagerEmail').value.trim()||null,manager_phone:q('artistEditManagerPhone').value.trim()||null,tax_number:q('artistEditTax').value.trim()||null,billing_name:q('artistEditBillingName').value.trim()||null,billing_email:q('artistEditBillingEmail1').value.trim()||null,billing_email_2:q('artistEditBillingEmail2').value.trim()||null,billing_email_3:q('artistEditBillingEmail3').value.trim()||null,billing_address:q('artistEditBillingAddress').value.trim()||null,notes:q('artistEditNotes').value.trim()||null,updated_at:new Date().toISOString()};
    const r=await sb.from('artists').update(patch).eq('id',id).select('*').single(); if(r.error)return toast(r.error.message);q('artistEditDialog').close();toast('Artista atualizado');await loadAll();
  }
  function injectButtons(){
    const cards=[...(q('artistList')?.querySelectorAll('.item')||[])];cards.forEach((card,i)=>{const a=artists[i];if(!a)return;let actions=card.querySelector('.file-actions');if(!actions){actions=document.createElement('div');actions.className='file-actions';card.appendChild(actions)}if(can('artists_manage')&&!actions.querySelector('[data-artist-edit]')){const b=document.createElement('button');b.type='button';b.className='secondary tiny';b.textContent='Editar';b.dataset.artistEdit=a.id;b.onclick=e=>{e.stopPropagation();openArtistEdit(a.id)};const f=actions.querySelector('[data-artist-files]');f?actions.insertBefore(b,f):actions.appendChild(b)}});
  }
  function patchForms(){
    if(q('artistEditForm'))q('artistEditForm').onsubmit=saveArtist;
    if(q('artistForm'))q('artistForm').onsubmit=async e=>{e.preventDefault();if(!can('artists_manage'))return toast('Sem permissão.');const {data:{user}}=await sb.auth.getUser();const r=await sb.from('artists').insert({name:q('artistName').value.trim(),base_fee:q('artistFee').value||null,contact_phone:q('artistPhone').value.trim()||null,contact_email:q('artistEmail').value.trim()||null,manager_name:q('artistManagerName')?.value.trim()||null,manager_email:q('artistManagerEmail')?.value.trim()||null,manager_phone:q('artistManagerPhone')?.value.trim()||null,billing_name:q('artistBillingName')?.value.trim()||null,tax_number:q('artistTaxNumber')?.value.trim()||null,billing_email:q('artistBillingEmail1')?.value.trim()||null,billing_email_2:q('artistBillingEmail2')?.value.trim()||null,billing_email_3:q('artistBillingEmail3')?.value.trim()||null,billing_address:q('artistBillingAddress')?.value.trim()||null,notes:q('artistNotes').value.trim()||null,created_by:user.id});if(r.error)return toast(r.error.message);q('artistDialog').close();e.target.reset();toast('Artista guardado');await loadAll()};
    if(q('memberForm'))q('memberForm').onsubmit=async e=>{e.preventDefault();const permissions={};document.querySelectorAll('[data-member-perm]').forEach(c=>permissions[c.dataset.memberPerm]=c.checked);const r=await sb.functions.invoke('update-team-member',{body:{id:q('memberId').value,email:q('memberEmail')?.value.trim()||null,full_name:q('memberName').value.trim(),phone:q('memberPhone').value.trim(),nif:q('memberNif').value.trim(),identification_number:q('memberIdNumber').value.trim(),role:q('memberRole').value,active:q('memberActive').checked,permissions}});if(r.error||!r.data?.ok)return toast(r.data?.error||r.error?.message||'Erro ao guardar');q('memberDialog').close();toast('Membro atualizado');await loadAll()};
  }
  function refresh(){ensureUI();patchForms();injectButtons()}
  addEventListener('load',()=>{refresh();setTimeout(refresh,500);setTimeout(refresh,1500);const list=q('artistList');if(list)new MutationObserver(()=>injectButtons()).observe(list,{childList:true,subtree:true});});
})();