(()=>{
const q=id=>document.getElementById(id);let loadedFor='',saving=false;
const allowedRole=r=>['partner','admin'].includes(String(r||''));
const teamRows=()=>{try{return Array.isArray(team)?team:[]}catch(_){return[]}};
function target(){const id=String(q('memberId')?.value||'');const p=teamRows().find(x=>String(x.id)===id)||(String(me?.id||'')===id?me:null);return {id,role:p?.role||q('memberRole')?.value||''}}
function ensure(){const form=q('memberForm');if(!form||q('billingDetailsSection'))return;const actions=form.querySelector('.actions');const box=document.createElement('fieldset');box.id='billingDetailsSection';box.className='hidden';box.innerHTML=`<legend>Dados para faturação</legend><label>Nome / nome fiscal<input id="billingName" autocomplete="name"></label><label>Nome da empresa<input id="billingCompany" autocomplete="organization" placeholder="Opcional"></label><label>NIF / Nº contribuinte<input id="billingTaxId"></label><label>Morada<input id="billingAddress" autocomplete="street-address"></label><div class="td-billing-grid"><label>Código postal<input id="billingPostalCode" autocomplete="postal-code"></label><label>Localidade<input id="billingCity"></label></div><label>País<input id="billingCountry" value="Portugal"></label><label>E-mail para faturação<input id="billingEmail" type="email"></label><label>Telefone<input id="billingPhone" type="tel"></label><div class="actions"><button type="button" class="secondary" id="saveBillingDetails">Guardar dados de faturação</button></div><div class="td-billing-share"><strong>Enviar dados de faturação</strong><small>Partilha apenas os dados preenchidos.</small><div class="actions"><button type="button" class="secondary" id="shareBillingWhatsApp">WhatsApp</button><button type="button" class="secondary" id="shareBillingEmail">E-mail</button></div></div>`;(actions?.parentNode||form).insertBefore(box,actions||null);q('saveBillingDetails').onclick=()=>saveCurrent();q('shareBillingWhatsApp').onclick=()=>share('whatsapp');q('shareBillingEmail').onclick=()=>share('email');const style=document.createElement('style');style.textContent='.td-billing-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.td-billing-share{margin-top:16px;padding-top:14px;border-top:1px solid rgba(255,255,255,.12)}.td-billing-share>small{display:block;margin:4px 0 10px;opacity:.72}@media(max-width:520px){.td-billing-grid{grid-template-columns:1fr}}';document.head.appendChild(style)}
function values(){return {billing_name:q('billingName')?.value.trim()||null,company_name:q('billingCompany')?.value.trim()||null,tax_id:q('billingTaxId')?.value.trim()||null,address:q('billingAddress')?.value.trim()||null,postal_code:q('billingPostalCode')?.value.trim()||null,city:q('billingCity')?.value.trim()||null,country:q('billingCountry')?.value.trim()||'Portugal',billing_email:q('billingEmail')?.value.trim()||null,billing_phone:q('billingPhone')?.value.trim()||null}}
function fill(d={}){if(!q('billingName'))return;q('billingName').value=d.billing_name||'';q('billingCompany').value=d.company_name||'';q('billingTaxId').value=d.tax_id||'';q('billingAddress').value=d.address||'';q('billingPostalCode').value=d.postal_code||'';q('billingCity').value=d.city||'';q('billingCountry').value=d.country||'Portugal';q('billingEmail').value=d.billing_email||'';q('billingPhone').value=d.billing_phone||''}
async function privateNifFor(t){try{if(String(t.id)===String(me?.id||'')){const r=await sb.rpc('my_private_profile');if(!r.error)return String(r.data?.[0]?.nif||'')}if(me?.role==='admin'){const r=await sb.from('team_travel_documents').select('nif').eq('user_id',t.id).maybeSingle();if(!r.error)return String(r.data?.nif||'')}}catch(_){}return''}
async function load(force=false){ensure();const t=target(),sec=q('billingDetailsSection');if(!sec)return;if(!t.id||!allowedRole(t.role)){sec.classList.add('hidden');loadedFor='';return}sec.classList.remove('hidden');if(!force&&loadedFor===t.id)return;loadedFor=t.id;fill({});const [r,nif]=await Promise.all([sb.from('billing_details').select('*').eq('user_id',t.id).maybeSingle(),privateNifFor(t)]);if(r.error)return toast('Não foi possível carregar os dados de faturação.');if(r.data)fill(r.data);if(q('memberNif')&&nif)q('memberNif').value=nif;if(q('billingTaxId')&&!q('billingTaxId').value&&nif)q('billingTaxId').value=nif}
async function saveCurrent(opts={}){if(saving)return false;const t=target();if(!t.id||!allowedRole(t.role))return true;const v=values();if(v.billing_email&&!/^\S+@\S+\.\S+$/.test(v.billing_email)){if(!opts.silent)toast('Confirma o e-mail de faturação.');return false}saving=true;try{const r=await sb.functions.invoke('save-billing-details',{body:{user_id:t.id,...v}});if(r.error||!r.data?.ok){toast(r.data?.error||r.error?.message||'Erro ao guardar dados de faturação');return false}const saved=r.data.billing||{};fill(saved);loadedFor=t.id;const verify=await sb.from('billing_details').select('*').eq('user_id',t.id).single();if(verify.error){toast('Os dados foram enviados, mas não foi possível confirmar a gravação.');return false}fill(verify.data);if(!opts.silent)toast('Dados de faturação guardados e confirmados');return true}finally{saving=false}}
function text(){const v=values(),name=v.company_name||v.billing_name||'';const lines=['Dados para faturação'];if(v.billing_name)lines.push(`Nome / nome fiscal: ${v.billing_name}`);if(v.company_name)lines.push(`Empresa: ${v.company_name}`);if(v.tax_id)lines.push(`NIF: ${v.tax_id}`);if(v.address)lines.push(`Morada: ${v.address}`);const loc=[v.postal_code,v.city].filter(Boolean).join(' ');if(loc)lines.push(`Código postal / Localidade: ${loc}`);if(v.country)lines.push(`País: ${v.country}`);if(v.billing_email)lines.push(`E-mail: ${v.billing_email}`);if(v.billing_phone)lines.push(`Telefone: ${v.billing_phone}`);return {body:lines.join('\n'),name}}
async function share(kind){const data=text();if(data.body.split('\n').length<2)return toast('Preenche primeiro os dados de faturação.');if(!await saveCurrent({silent:true}))return;const body=encodeURIComponent(data.body);if(kind==='whatsapp')window.open(`https://wa.me/?text=${body}`,'_blank');else window.location.href=`mailto:?subject=${encodeURIComponent('Dados de faturação'+(data.name?' – '+data.name:''))}&body=${body}`}
function wireMainSave(){const f=q('memberForm');if(!f||f.dataset.billingMainSaveWired)return;f.dataset.billingMainSaveWired='1';f.addEventListener('submit',async e=>{const t=target();if(!allowedRole(t.role))return;if(!await saveCurrent({silent:true})){e.preventDefault();e.stopImmediatePropagation()}},true)}
function refresh(){ensure();wireMainSave();load(true)}
function boot(){ensure();wireMainSave();const d=q('memberDialog');if(d&&!d.dataset.billingWired){d.dataset.billingWired='1';new MutationObserver(()=>{if(d.open)setTimeout(()=>load(true),20)}).observe(d,{attributes:true,attributeFilter:['open']})}q('memberRole')?.addEventListener('change',()=>setTimeout(()=>load(true),0));setTimeout(()=>load(false),250)}
if(document.readyState==='loading')addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.TeamDuckBillingDetails={refresh,load,saveCurrent};
})();
