(()=>{
const COLORS=['#54d96b','#f2b72f','#38a9e8','#9b6cff','#ff6b57','#2fd0b2','#e065b8','#7fd13b','#ff8f3d','#55b7ff'];
const byId=id=>(concerts||[]).find(c=>String(c.id)===String(id));
const hash=s=>{let h=0;for(const ch of String(s||''))h=((h<<5)-h)+ch.charCodeAt(0)|0;return Math.abs(h)};
const artistColor=c=>COLORS[hash(c?.artist_id||c?.artists?.name)%COLORS.length];
const techFor=c=>{const ass=(c?.concert_assignments||[]).find(a=>!a.replaced_by_id)||null;return ass?.profiles?.full_name||c?.technician_name||''};
const fmtDate=v=>{const d=new Date(v);if(Number.isNaN(d))return'';return new Intl.DateTimeFormat('pt-PT',{day:'2-digit',month:'2-digit',year:'numeric'}).format(d)};
const fmtTime=v=>{const d=new Date(v);if(Number.isNaN(d))return'';return new Intl.DateTimeFormat('pt-PT',{hour:'2-digit',minute:'2-digit'}).format(d)};
function ensureDetailDialog(){if(document.getElementById('tdCompactDetail'))return;document.body.insertAdjacentHTML('beforeend',`<dialog id="tdCompactDetail" class="td-detail-dialog"><div class="td-detail-shell"><div class="td-detail-head"><button type="button" class="secondary tiny" data-td-close>←</button><div><strong id="tdDetailArtist">Trabalho</strong><small id="tdDetailWhen"></small></div><button type="button" class="secondary tiny" data-td-close>✕</button></div><div id="tdDetailSummary" class="td-detail-summary"></div><div><h4>Ações rápidas</h4><div id="tdDetailActions" class="td-detail-actions"></div></div><div><h4>Informação detalhada</h4><div id="tdDetailInfo" class="td-detail-info"></div></div></div></dialog>`);const d=document.getElementById('tdCompactDetail');d.querySelectorAll('[data-td-close]').forEach(b=>b.onclick=()=>d.close());d.addEventListener('close',restoreActions)}
let movedActions=null,movedParent=null,movedNext=null;
function restoreActions(){if(movedActions&&movedParent){if(movedNext&&movedNext.parentNode===movedParent)movedParent.insertBefore(movedActions,movedNext);else movedParent.appendChild(movedActions)}movedActions=movedParent=movedNext=null}
function openDetail(card,id){const c=byId(id);if(!c)return;ensureDetailDialog();restoreActions();const d=document.getElementById('tdCompactDetail'),color=artistColor(c);d.style.setProperty('--artist-color',color);document.getElementById('tdDetailArtist').textContent=c.artists?.name||'Trabalho';document.getElementById('tdDetailWhen').textContent=`${fmtDate(c.starts_at)}, ${fmtTime(c.starts_at)} · ${c.city||c.venue||'Local por definir'} · ${c.work_position||''}`;const tech=techFor(c)||card.querySelector('.tech-name')?.textContent?.replace(/^.*?:\s*/,'')||'—';const fee=typeof money==='function'?money(c.fee_override):`${Number(c.fee_override||0).toFixed(2)} €`;document.getElementById('tdDetailSummary').innerHTML=`<div><span>Técnico principal</span><b>${esc(tech)}</b></div><div><span>Valor total</span><b class="money">${fee}</b></div><div><span>Função</span><b>${esc(c.work_position||'—')}</b></div><div><span>Estado</span><b>${c.closed?'Fechado':(c.status==='confirmed'?'Aceite':'Ativo')}</b></div>`;document.getElementById('tdDetailInfo').innerHTML=`<div><span>Data e hora</span><b>${fmtDate(c.starts_at)} · ${fmtTime(c.starts_at)}</b></div><div><span>Local</span><b>${esc(c.city||c.venue||'Por definir')}</b></div><div><span>Função</span><b>${esc(c.work_position||'—')}</b></div>${can?.('financials_view')?`<div><span>Valor total</span><b>${fee}</b></div>`:''}<div><span>Técnico principal</span><b>${esc(tech)}</b></div>`;const actions=card.querySelector('.concert-actions');const host=document.getElementById('tdDetailActions');host.innerHTML='';if(actions){movedActions=actions;movedParent=actions.parentNode;movedNext=actions.nextSibling;host.appendChild(actions);actions.classList.add('td-actions-in-detail')}if(!host.children.length)host.innerHTML='<span class="muted">Sem ações disponíveis para este perfil.</span>';d.showModal()}
function compactCard(card){if(card.dataset.tdCompact==='1')return;const viewBtn=card.querySelector('[data-concert-view]');const id=viewBtn?.dataset.concertView||card.querySelector('[data-share-invite]')?.dataset.shareInvite||'';if(!id)return;const c=byId(id);if(!c)return;card.dataset.tdCompact='1';card.dataset.concertId=id;card.style.setProperty('--artist-color',artistColor(c));const existing=card.querySelector(':scope > div:first-child');const tech=(techFor(c)||card.querySelector('.tech-name')?.textContent?.replace(/^.*?:\s*/,'')||'').trim();const d=new Date(c.starts_at);const day=String(d.getDate()).padStart(2,'0'),mon=d.toLocaleDateString('pt-PT',{month:'short'}).replace('.','').toUpperCase();const summary=document.createElement('div');summary.className='td-compact-summary';summary.innerHTML=`<div class="td-date-block"><b>${day}</b><span>${mon}</span></div><div class="td-compact-main"><strong>${esc(c.artists?.name||'Trabalho')}</strong>${tech?`<span class="td-tech-dot"><i></i>${esc(tech)}${c.work_position?` (${esc(c.work_position)})`:''}</span>`:''}<span class="td-time">◷ ${fmtTime(c.starts_at)}</span></div><span class="td-position">${esc(c.work_position||'')}</span>`;card.insertBefore(summary,card.firstChild);[...card.children].forEach(ch=>{if(ch!==summary)ch.classList.add('td-compact-hidden')});card.setAttribute('role','button');card.tabIndex=0;const go=e=>{if(e.target.closest('button,a,input,select,textarea'))return;openDetail(card,id)};card.addEventListener('click',go);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openDetail(card,id)}})}
function refresh(){document.querySelectorAll('#concerts>.item,#nextWeekConcerts>.item,#nextMonthConcerts>.item,#nextConcerts>.item').forEach(compactCard)}
function boot(){ensureDetailDialog();setTimeout(refresh,300);setTimeout(refresh,900);['concerts','nextWeekConcerts','nextMonthConcerts','nextConcerts'].forEach(id=>{const h=document.getElementById(id);if(h)new MutationObserver(()=>setTimeout(refresh,40)).observe(h,{childList:true,subtree:true})})}
if(document.readyState==='loading')addEventListener('load',boot,{once:true});else boot();window.TeamDuckCompactAgenda={refresh,openDetail};
})();