(()=>{
const COLORS=['#54d96b','#f2b72f','#38a9e8','#9b6cff','#ff6b57','#2fd0b2','#e065b8','#7fd13b','#ff8f3d','#55b7ff'];let refreshTimer=null;
const allConcerts=()=>{try{return Array.isArray(concerts)?concerts:[]}catch(_){return[]}};const allTeam=()=>{try{return Array.isArray(team)?team:[]}catch(_){return[]}};
const escSafe=v=>{try{return typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}catch(_){return String(v??'')}};
const hash=s=>{let h=0;for(const ch of String(s||''))h=((h<<5)-h)+ch.charCodeAt(0)|0;return Math.abs(h)};const artistColor=c=>COLORS[hash(c?.artist_id||c?.artists?.name)%COLORS.length];
const personFor=c=>allTeam().find(p=>String(p.id)===String(c?.principal_technician_id||c?.technician_id||''))||null;
const techName=c=>{const p=personFor(c);if(p)return p.full_name||p.email||'';return c?.technician_name||''};
const fmtDate=v=>{const d=new Date(v);if(Number.isNaN(d.getTime()))return'';return new Intl.DateTimeFormat('pt-PT',{day:'2-digit',month:'2-digit',year:'numeric'}).format(d)};const fmtTime=v=>{const d=new Date(v);if(Number.isNaN(d.getTime()))return'';return new Intl.DateTimeFormat('pt-PT',{hour:'2-digit',minute:'2-digit'}).format(d)};
function canViewFinancials(){try{return typeof can==='function'?can('financials_view'):false}catch(_){return false}}function moneySafe(v){try{return typeof money==='function'?money(v):`${Number(v||0).toFixed(2)} €`}catch(_){return `${Number(v||0).toFixed(2)} €`}}
function ensureDetailDialog(){if(document.getElementById('tdCompactDetail'))return;document.body.insertAdjacentHTML('beforeend',`<dialog id="tdCompactDetail" class="td-detail-dialog"><div class="td-detail-shell"><div class="td-detail-head"><button type="button" class="secondary tiny" data-td-close>←</button><div><strong id="tdDetailArtist">Trabalho</strong><small id="tdDetailWhen"></small></div><button type="button" class="secondary tiny" data-td-close>✕</button></div><div id="tdDetailSummary" class="td-detail-summary"></div><div><h4>Ações rápidas</h4><div id="tdDetailActions" class="td-detail-actions"></div></div><div><h4>Informação detalhada</h4><div id="tdDetailInfo" class="td-detail-info"></div></div></div></dialog>`);const d=document.getElementById('tdCompactDetail');d.querySelectorAll('[data-td-close]').forEach(b=>b.onclick=()=>d.close());d.addEventListener('click',e=>{if(e.target===d)d.close()})}
function actionProxy(source,label=null){if(!source||source.disabled)return null;const b=document.createElement('button');b.type='button';b.className=source.className||'secondary';b.textContent=label||source.textContent?.trim()||'Abrir';b.onclick=e=>{e.stopPropagation();document.getElementById('tdCompactDetail')?.close();setTimeout(()=>source.click(),30)};return b}
function renderActions(card){const host=document.getElementById('tdDetailActions');host.innerHTML='';const seen=new Set(),add=(source,label)=>{if(!source||source.closest('.hidden'))return;const key=label||source.textContent?.trim();if(!key||seen.has(key))return;seen.add(key);const p=actionProxy(source,label);if(p)host.appendChild(p)};add(card.querySelector('[data-concert-view]'),'Ver / Editar');card.querySelectorAll('.concert-actions button').forEach(b=>add(b));if(!host.children.length)host.innerHTML='<span class="muted">Sem ações disponíveis para este perfil.</span>'}
function openDetail(card,id){const c=allConcerts().find(x=>String(x.id)===String(id));if(!c)return;ensureDetailDialog();const d=document.getElementById('tdCompactDetail');d.style.setProperty('--artist-color',artistColor(c));document.getElementById('tdDetailArtist').textContent=c.artists?.name||'Trabalho';document.getElementById('tdDetailWhen').textContent=`${fmtDate(c.starts_at)}, ${fmtTime(c.starts_at)} · ${c.city||c.venue||'Local por definir'} · ${c.work_position||''}`;const tech=techName(c)||'—',fee=moneySafe(c.fee_override);document.getElementById('tdDetailSummary').innerHTML=`<div><span>Técnico principal</span><b>${escSafe(tech)}</b></div>${canViewFinancials()?`<div><span>Valor total</span><b class="money">${fee}</b></div>`:''}<div><span>Função</span><b>${escSafe(c.work_position||'—')}</b></div><div><span>Estado</span><b>${c.closed?'Fechado':(c.status==='confirmed'?'Aceite':'Ativo')}</b></div>`;document.getElementById('tdDetailInfo').innerHTML=`<div><span>Data e hora</span><b>${fmtDate(c.starts_at)} · ${fmtTime(c.starts_at)}</b></div><div><span>Local</span><b>${escSafe(c.city||c.venue||'Por definir')}</b></div><div><span>Função</span><b>${escSafe(c.work_position||'—')}</b></div>${canViewFinancials()?`<div><span>Valor total</span><b>${fee}</b></div>`:''}<div><span>Técnico principal</span><b>${escSafe(tech)}</b></div>`;renderActions(card);if(!d.open)d.showModal()}
function inferConcert(card,index){const direct=card.querySelector('[data-concert-view]')?.dataset.concertView||card.dataset.concertId;if(direct)return allConcerts().find(c=>String(c.id)===String(direct))||null;const host=card.parentElement?.id;if(host==='concerts')return allConcerts()[index]||null;if(host==='nextConcerts')return allConcerts().filter(c=>new Date(c.starts_at)>=new Date()&&!c.closed).slice(0,5)[index]||null;const txt=(card.textContent||'').toLowerCase();return allConcerts().find(c=>txt.includes(String(c.artists?.name||'').toLowerCase())&&txt.includes(new Date(c.starts_at).toLocaleDateString('pt-PT',{day:'2-digit',month:'2-digit'}).toLowerCase()))||null}
async function hydrateTechPhoto(summary,p){const img=summary.querySelector('[data-td-tech-photo]');if(!img||!p)return;try{const u=await window.TeamDuckImages?.signed?.(p.photo_path);if(u&&img.isConnected)img.src=u}catch(_){ }if(!img.dataset.wired){img.dataset.wired='1';img.addEventListener('click',e=>{e.stopPropagation();window.TeamDuckImages?.showPersonPhoto?.(p)})}}
function compactCard(card,index){const c=inferConcert(card,index);if(!c)return;const id=String(c.id);card.dataset.concertId=id;card.style.setProperty('--artist-color',artistColor(c));let summary=card.querySelector(':scope > .td-compact-summary');if(!summary){summary=document.createElement('div');summary.className='td-compact-summary';card.insertBefore(summary,card.firstChild)}const p=personFor(c),tech=techName(c),d=new Date(c.starts_at),day=String(d.getDate()).padStart(2,'0'),mon=d.toLocaleDateString('pt-PT',{month:'short'}).replace('.','').toUpperCase(),photo=p?`<img data-td-tech-photo class="td-compact-tech-photo" src="401FB0DA-DAD2-49CE-89E0-A9850A0722F7.png" alt="${escSafe(tech)}">`:'';const html=`<div class="td-date-block"><b>${day}</b><span>${mon}</span></div><div class="td-compact-main"><strong>${escSafe(c.artists?.name||'Trabalho')}</strong>${tech?`<span class="td-tech-dot">${photo}<span>${escSafe(tech)}${c.work_position?` (${escSafe(c.work_position)})`:''}</span></span>`:''}<span class="td-time">◷ ${fmtTime(c.starts_at)}</span></div><span class="td-position">${escSafe(c.work_position||'')}</span>`;if(summary.dataset.snapshot!==html){summary.dataset.snapshot=html;summary.innerHTML=html;if(p)hydrateTechPhoto(summary,p)}[...card.children].forEach(ch=>ch.classList.toggle('td-compact-hidden',ch!==summary));if(card.dataset.tdCompact!=='1'){card.dataset.tdCompact='1';card.setAttribute('role','button');card.tabIndex=0;const go=e=>{if(e.target.closest('button,a,input,select,textarea,[data-td-tech-photo]'))return;openDetail(card,id)};card.addEventListener('click',go);card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openDetail(card,id)}})}}
function refresh(){['concerts','nextWeekConcerts','nextMonthConcerts','nextConcerts'].forEach(id=>{const h=document.getElementById(id);if(!h)return;[...h.querySelectorAll(':scope > .item')].forEach((card,i)=>compactCard(card,i))})}
function schedule(ms=60){clearTimeout(refreshTimer);refreshTimer=setTimeout(refresh,ms)}
function boot(){ensureDetailDialog();schedule(120);document.querySelectorAll('#nav button[data-page="agenda"],#nav button[data-page="dashboard"]').forEach(b=>b.addEventListener('click',()=>schedule(60)));if(typeof window.loadAll==='function'&&!window.__compactLoadAllPatched){const old=window.loadAll;window.loadAll=async function(...args){const r=await old.apply(this,args);schedule(80);return r};window.__compactLoadAllPatched=true}const s=document.createElement('style');s.textContent='.td-tech-dot{display:flex!important;align-items:center;gap:7px}.td-compact-tech-photo{width:28px;height:28px;border-radius:50%;object-fit:cover;border:1px solid rgba(255,255,255,.18);background:#0b2b19;cursor:pointer;flex:0 0 auto}.td-compact-tech-photo:active{transform:scale(.96)}';document.head.appendChild(s)}
if(document.readyState==='loading')addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.TeamDuckCompactAgenda={refresh:()=>schedule(0),openDetail};
})();
