(()=>{
const q=id=>document.getElementById(id);let editingId=null,refreshTimer=null;
const localDT=v=>{if(!v)return'';const d=new Date(v),z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`};
const isPast=c=>{const end=c?.ends_at||c?.starts_at;if(!end)return false;const d=new Date(end);return !Number.isNaN(d.getTime())&&d.getTime()<Date.now()};
function ensureDialog(){if(q('concertViewDialog'))return;document.body.insertAdjacentHTML('beforeend',`<dialog id="concertViewDialog"><form id="concertEditForm"><div class="title-row"><h3 id="concertViewTitle">Trabalho</h3><button type="button" id="concertViewClose">Fechar</button></div><label>Artista<select id="editConcertArtist"></select></label><label>Início<input id="editConcertStart" type="datetime-local"></label><label>Fim<input id="editConcertEnd" type="datetime-local"></label><label>Local / Morada<input id="editConcertVenue"></label><label>Cidade<input id="editConcertCity"></label><label>Função<select id="editConcertPosition"><option value="FOH">FOH</option><option value="ROH">ROH</option><option value="FOH+ROH">FOH + ROH</option></select></label><label>Call time<input id="editConcertCall" type="time"></label><label>Soundcheck<input id="editConcertSoundcheck" type="time"></label><label>Show<input id="editConcertShow" type="time"></label><label>Notas<textarea id="editConcertNotes"></textarea></label><div id="editFinancials"><label>Cachet (€)<input id="editConcertFee" type="number" step=".01"></label><label>Recebido (€)<input id="editConcertReceived" type="number" step=".01"></label></div><div class="actions"><button type="button" id="concertEditCancel" class="secondary">Cancelar</button><button type="submit">Guardar alterações</button></div></form></dialog>`);q('concertViewClose').onclick=q('concertEditCancel').onclick=()=>q('concertViewDialog').close();q('concertEditForm').onsubmit=saveEdit}
function ensureStyles(){if(q('tdBillingWorkflowStyle'))return;const s=document.createElement('style');s.id='tdBillingWorkflowStyle';s.textContent='.concert-actions [data-invoice].td-invoiced{background:#6f7672!important;border-color:#6f7672!important;color:#eef0ef!important;box-shadow:none!important}.concert-actions [data-paid]{font-weight:850}.concert-actions [data-paid].td-paid{background:#47504b!important;border-color:#47504b!important;color:#fff!important}';document.head.appendChild(s)}
function openConcertView(id){const c=(concerts||[]).find(x=>String(x.id)===String(id));if(!c)return;ensureDialog();editingId=c.id;q('concertViewTitle').textContent=`${c.artists?.name||'Trabalho'} · Ver e Editar`;q('editConcertArtist').innerHTML=(artists||[]).map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('');q('editConcertArtist').value=c.artist_id||'';q('editConcertStart').value=localDT(c.starts_at);q('editConcertEnd').value=localDT(c.ends_at);q('editConcertVenue').value=c.venue||'';q('editConcertCity').value=c.city||'';q('editConcertPosition').value=String(c.work_position||'FOH').replace(/\s*\+\s*/g,'+');q('editConcertCall').value=c.call_time||'';q('editConcertSoundcheck').value=c.soundcheck_time||'';q('editConcertShow').value=c.show_time||'';q('editConcertNotes').value=c.notes||'';q('editFinancials').style.display=can('financials_view')?'':'none';q('editConcertFee').value=c.fee_override??'';q('editConcertReceived').value=c.amount_received??0;if(!q('concertViewDialog').open)q('concertViewDialog').showModal()}
async function saveEdit(e){e.preventDefault();if(!can('concerts_manage'))return toast('Sem permissão para editar.');const patch={artist_id:q('editConcertArtist').value,starts_at:new Date(q('editConcertStart').value).toISOString(),ends_at:q('editConcertEnd').value?new Date(q('editConcertEnd').value).toISOString():null,venue:q('editConcertVenue').value||null,city:q('editConcertCity').value||null,work_position:q('editConcertPosition').value,call_time:q('editConcertCall').value||null,soundcheck_time:q('editConcertSoundcheck').value||null,show_time:q('editConcertShow').value||null,notes:q('editConcertNotes').value||null};if(can('financials_view')){patch.fee_override=q('editConcertFee').value||null;patch.amount_received=q('editConcertReceived').value||0}const r=await sb.from('concerts').update(patch).eq('id',editingId);if(r.error)return toast(r.error.message);q('concertViewDialog').close();toast('Trabalho atualizado');await loadAll()}
async function toggleInvoice(c){if(!isPast(c)||c.closed)return;const next=!c.receipt_issued,r=await sb.from('concerts').update({receipt_issued:next,receipt_issued_at:next?new Date().toISOString():null}).eq('id',c.id);if(r.error)return toast(r.error.message);toast(next?'Marcado como faturado':'Faturado removido');await loadAll()}
async function markPaid(c){if(!isPast(c)||c.closed)return;const value=Number(c.fee_override||0),r=await sb.from('concerts').update({amount_received:value,payment_received_at:new Date().toISOString(),closed:true,progress_percent:100}).eq('id',c.id);if(r.error)return toast(r.error.message);toast('Pago · trabalho passou para Fechados');await loadAll()}
function decorate(container,arr){if(!container)return;[...container.querySelectorAll(':scope > .item')].forEach((card,i)=>{const c=arr[i];if(!c)return;card.dataset.concertId=String(c.id);let actions=card.querySelector('.concert-actions');if(!actions){actions=document.createElement('div');actions.className='concert-actions';card.appendChild(actions)}let v=actions.querySelector('[data-concert-view]');if(!v){v=document.createElement('button');v.type='button';v.className='secondary tiny';actions.prepend(v)}v.dataset.concertView=c.id;v.textContent='Ver';v.onclick=e=>{e.stopPropagation();openConcertView(c.id)};actions.querySelectorAll('[data-invoice],[data-paid]').forEach(b=>b.remove());if(isPast(c)&&!c.closed){let f=document.createElement('button');f.type='button';f.className='secondary tiny';f.dataset.invoice=c.id;f.onclick=e=>{e.stopPropagation();toggleInvoice(c)};f.textContent=c.receipt_issued?'✓ Faturado':'Faturado';f.classList.toggle('td-invoiced',!!c.receipt_issued);actions.appendChild(f);let p=document.createElement('button');p.type='button';p.className='secondary tiny';p.dataset.paid=c.id;p.onclick=e=>{e.stopPropagation();markPaid(c)};p.textContent='Pago';actions.appendChild(p)}})}
function renderClosed(){const host=q('closedConcerts');if(!host)return;const rows=(concerts||[]).filter(c=>c.closed).sort((a,b)=>new Date(b.starts_at)-new Date(a.starts_at));host.innerHTML=rows.length?rows.map(c=>`<article class="item" data-concert-id="${c.id}"><div><strong>${esc(c.artists?.name||'Trabalho')}</strong><small>${dt(c.starts_at)} · ${esc(c.city||c.venue||'Local por definir')} · ${esc(c.work_position||'')}</small><small>${c.payment_received_at?'✓ Pago · ':''}Fechado${c.receipt_issued?' · Faturado':''}</small></div><div class="concert-actions"><button type="button" class="secondary tiny" data-closed-view="${c.id}">Ver</button></div></article>`).join(''):'<div class="empty">Ainda não existem trabalhos fechados.</div>';host.querySelectorAll('[data-closed-view]').forEach(b=>b.onclick=()=>openConcertView(b.dataset.closedView))}
function refresh(){clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>{ensureDialog();ensureStyles();const active=(concerts||[]).filter(c=>!c.closed);decorate(q('concerts'),active);const future=active.filter(c=>new Date(c.starts_at)>=new Date()).slice(0,5);decorate(q('nextConcerts'),future);renderClosed();window.TeamDuckCompactAgenda?.refresh?.()},40)}
function boot(){refresh();if(typeof window.loadAll==='function'&&!window.__concertViewLoadAllPatched){const old=window.loadAll;window.loadAll=async function(...args){const r=await old.apply(this,args);refresh();return r};window.__concertViewLoadAllPatched=true}document.querySelector('#nav button[data-page="closed"]')?.addEventListener('click',renderClosed)}
if(document.readyState==='loading')addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.openConcertView=openConcertView;window.TeamDuckConcertView={refresh};
})();
