(()=>{
let concerts=[];
function say(m){try{if(typeof toast==='function')toast(m);else alert(m)}catch(_){alert(m)}}
async function refresh(){try{const r=await sb.from('concerts').select('id,starts_at,venue,city,work_position,technician_id,closed,booking_status,status,artists(name)').order('starts_at');if(r.error)throw r.error;concerts=r.data||[];return true}catch(e){console.warn('share refresh',e);return false}}
function core(c){const d=new Date(c.starts_at);const date=d.toLocaleDateString('pt-PT',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'});const time=d.toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'});const place=[c.venue,c.city].filter(Boolean).join(' · ')||'Por definir';return `🐥 TEAM DUCK — PEDIDO DE DISPONIBILIDADE\n\n🎤 ${c.artists?.name||'Trabalho'}\n📅 ${date}\n🕒 ${time}\n📍 ${place}\n🎚 ${c.work_position||'Por definir'}\n\nConfirma a tua disponibilidade no link:`}
async function linkFor(c){const r=await sb.functions.invoke('create-concert-share-link',{body:{concert_id:c.id}});if(r.error||!r.data?.ok)throw new Error(r.data?.error||r.error?.message||'Não foi possível criar o link');return r.data.invite_url}
async function share(c){try{const url=await linkFor(c);const text=`${core(c)}\n${url}`;if(navigator.share){try{await navigator.share({title:'Team Duck · Confirmar data',text,url});return}catch(e){if(e?.name==='AbortError')return}}const phone='';location.href=`https://wa.me/${phone}?text=${encodeURIComponent(text)}`}catch(e){console.warn(e);say(e?.message||'Não foi possível criar o convite.')}}
async function copy(c){try{const url=await linkFor(c);await navigator.clipboard.writeText(url);say('Link do convite copiado.')}catch(e){say(e?.message||'Não foi possível copiar o link.')}}
function decorate(){const host=document.getElementById('concerts');if(!host)return;const cards=[...host.querySelectorAll(':scope > .item')];cards.forEach((card,i)=>{const c=concerts[i];if(!c||c.closed)return;const actions=card.querySelector('.concert-actions');if(!actions)return;const old=[...actions.querySelectorAll('button')].find(b=>/WhatsApp · Confirmar|Partilhar convite/i.test(b.textContent||''));if(old){old.textContent='Partilhar convite';old.onclick=()=>share(c);old.dataset.shareInvite='1'}let cp=actions.querySelector('[data-copy-invite]');if(!cp){cp=document.createElement('button');cp.type='button';cp.className='secondary tiny';cp.textContent='Copiar link';cp.dataset.copyInvite='1';cp.onclick=()=>copy(c);actions.appendChild(cp)}else cp.onclick=()=>copy(c)})}
async function run(){await refresh();decorate()}
function observe(){const host=document.getElementById('concerts');if(!host||host.dataset.shareObserved)return;host.dataset.shareObserved='1';new MutationObserver(()=>setTimeout(run,120)).observe(host,{childList:true,subtree:true})}
addEventListener('load',()=>{run();observe();setTimeout(run,700);setTimeout(run,1600);document.querySelectorAll('#nav button[data-page="agenda"]').forEach(b=>b.addEventListener('click',()=>setTimeout(run,200)))})
window.TeamDuckShare={share,copy,refresh:run};
})();