(()=>{
const q=id=>document.getElementById(id);
const statusMeta={confirmed:{label:'Confirmado',cls:'s-green'},reserved:{label:'Reservado',cls:'s-yellow'},cancelled:{label:'Cancelado',cls:'s-red'}};
const responseMeta={accepted:{label:'Aceite pelo técnico',cls:'s-green'},pending:{label:'A aguardar resposta por e-mail',cls:'s-red'},declined:{label:'Recusado pelo técnico',cls:'s-red'}};
function acceptedStamp(c){if((c.technician_response||'pending')!=='accepted'||!c.technician_response_at)return'';const d=new Date(c.technician_response_at);return ` · ${d.toLocaleDateString('pt-PT',{day:'2-digit',month:'2-digit',year:'numeric'})} às ${d.toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'})}`}
function injectFields(){const form=q('concertForm');if(!form||q('concertTechnician'))return;const pos=q('concertPosition')?.closest('label');if(!pos)return;pos.insertAdjacentHTML('afterend',`<label>Técnico selecionado<select id="concertTechnician" required><option value="">Selecionar técnico</option></select></label><fieldset class="status-selector"><legend>Estado da data</legend><div class="status-three"><label><input type="radio" name="concertBookingStatus" value="confirmed"><span class="dot green"></span>Confirmado</label><label><input type="radio" name="concertBookingStatus" value="reserved" checked><span class="dot yellow"></span>Reservado</label><label><input type="radio" name="concertBookingStatus" value="cancelled"><span class="dot red"></span>Cancelado</label></div></fieldset>`);fillTechnicians()}
function fillTechnicians(){const sel=q('concertTechnician');if(!sel)return;const active=(team||[]).filter(p=>p.active!==false);const html='<option value="">Selecionar técnico</option>'+active.map(p=>`<option value="${p.id}">${esc(p.full_name||p.email||'Membro')} — ${esc(p.email||'sem e-mail')}</option>`).join('');if(sel.innerHTML!==html)sel.innerHTML=html}
function technicianName(c){const p=(team||[]).find(x=>x.id===c.technician_id);return p?.full_name||p?.email||'Sem técnico'}
function bookingStatus(c){return c.booking_status||((c.status==='cancelled')?'cancelled':(c.status==='confirmed'?'confirmed':'reserved'))}
function responseStatus(c){return c.technician_response||'pending'}
async function edgeErrorMessage(r){if(r?.data?.error)return r.data.error;const ctx=r?.error?.context;if(ctx){try{const body=await ctx.clone().json();if(body?.error)return body.error;if(body?.message)return body.message}catch(_){ }try{const text=await ctx.clone().text();if(text)return text}catch(_){ }}return r?.error?.message||'Não foi possível enviar o e-mail'}
async function sendTechnicianEmail(c,quiet=false){const r=await sb.functions.invoke('send-concert-invite',{body:{concert_id:c.id}});if(r.error||!r.data?.ok){const msg=await edgeErrorMessage(r);if(!quiet)toast('E-mail: '+msg);return false}if(!quiet)toast('Convite enviado por e-mail para '+(r.data.email||'o técnico'));return true}
function overlaps(a,b){const ae=new Date(a.ends_at||new Date(new Date(a.starts_at).getTime()+2*3600000)),be=new Date(b.ends_at||new Date(new Date(b.starts_at).getTime()+2*3600000));return new Date(a.starts_at)<be&&new Date(b.starts_at)<ae}
function conflictsFor(c,techId){return (concerts||[]).filter(x=>x.id!==c.id&&String(x.technician_id)===String(techId)&&x.booking_status!=='cancelled'&&x.status!=='cancelled'&&overlaps(c,x))}
async function changeTechnician(c){if(!can('concerts_manage'))return toast('Sem permissão.');const active=(team||[]).filter(p=>p.active!==false);const choices=active.map((p,i)=>`${i+1}. ${p.full_name||p.email}`).join('\n');const current=active.findIndex(p=>String(p.id)===String(c.technician_id));const raw=prompt(`Alterar técnico de ${c.artists?.name||'trabalho'}\n\n${choices}\n\nEscreve o número do novo técnico:`,current>=0?String(current+1):'');if(raw===null)return;const p=active[Number(raw)-1];if(!p)return toast('Técnico inválido.');const conflicts=conflictsFor(c,p.id);if(conflicts.length){const names=conflicts.map(x=>`${x.artists?.name||'Trabalho'} · ${dt(x.starts_at)}`).join('\n');if(!confirm(`ATENÇÃO: este técnico já tem ${conflicts.length} trabalho(s) sobreposto(s):\n\n${names}\n\nQueres atribuí-lo na mesma?`))return}const r=await sb.from('concerts').update({technician_id:p.id,technician_response:'pending',technician_response_at:null,technician_response_source:null,technician_response_email_sent_at:null}).eq('id',c.id);if(r.error)return toast(r.error.message);toast('Técnico alterado. A enviar novo convite…');await loadAll();const updated=(concerts||[]).find(x=>x.id===c.id)||{...c,technician_id:p.id};await sendTechnicianEmail(updated,true);await loadAll();toast(`Novo técnico: ${p.full_name||p.email}`)}
function decorateContainer(container,arr){if(!container)return;const cards=[...container.querySelectorAll('.item')];cards.forEach((card,i)=>{const c=arr[i];if(!c)return;let meta=card.querySelector('.concert-meta');if(!meta){meta=document.createElement('div');meta.className='concert-meta';card.querySelector('div:first-child')?.appendChild(meta)}const bs=statusMeta[bookingStatus(c)]||statusMeta.reserved,rs=responseMeta[responseStatus(c)]||responseMeta.pending;const sent=c.technician_response_email_sent_at?' · e-mail enviado':'';const accepted=acceptedStamp(c);meta.innerHTML=`<span class="status-chip ${bs.cls}"><i></i>${bs.label}</span><span class="status-chip ${rs.cls}"><i></i>${rs.label}${accepted}${responseStatus(c)==='accepted'?'':sent}</span><span class="tech-name">Técnico: ${esc(technicianName(c))}</span>`;let actions=card.querySelector('.concert-actions');if(!actions){actions=document.createElement('div');actions.className='concert-actions';card.appendChild(actions)}actions.querySelectorAll('[data-team-action]').forEach(x=>x.remove());if(can('concerts_manage')){const ch=document.createElement('button');ch.type='button';ch.className='secondary tiny';ch.textContent='Alterar técnico';ch.dataset.teamAction='change';ch.onclick=()=>changeTechnician(c);actions.appendChild(ch)}if(can('concerts_manage')&&c.technician_id&&responseStatus(c)==='pending'){const e=document.createElement('button');e.type='button';e.className='secondary tiny';e.textContent=c.technician_response_email_sent_at?'Reenviar e-mail':'Enviar e-mail';e.dataset.teamAction='email';e.onclick=()=>sendTechnicianEmail(c);actions.appendChild(e)}})}
function decorate(){const future=(concerts||[]).filter(c=>new Date(c.starts_at)>=new Date()&&!c.closed).slice(0,5);decorateContainer(q('concerts'),concerts||[]);decorateContainer(q('nextConcerts'),future)}
function patchSubmit(){const form=q('concertForm');if(!form||form.dataset.teamPatched)return;form.dataset.teamPatched='1';form.onsubmit=async e=>{e.preventDefault();if(!can('concerts_manage'))return toast('Sem permissão.');const tech=q('concertTechnician')?.value;if(!tech)return toast('Seleciona o técnico para esta data.');const draft={id:null,starts_at:new Date(q('concertStart').value).toISOString(),ends_at:q('concertEnd').value?new Date(q('concertEnd').value).toISOString():null};const conflicts=conflictsFor(draft,tech);if(conflicts.length&&!confirm(`Este técnico já tem ${conflicts.length} trabalho(s) sobreposto(s). Queres criar a data na mesma?`))return;const {data:{user}}=await sb.auth.getUser();const booking=document.querySelector('input[name="concertBookingStatus"]:checked')?.value||'reserved';const r=await sb.from('concerts').insert({artist_id:q('concertArtist').value,starts_at:draft.starts_at,ends_at:draft.ends_at,venue:q('concertVenue').value||null,city:q('concertCity').value||null,work_position:q('concertPosition').value,technician_id:tech,booking_status:booking,technician_response:'pending',fee_override:q('concertFee').value||null,amount_received:q('concertReceived').value||0,notes:q('concertNotes').value||null,status:booking==='cancelled'?'cancelled':'confirmed',created_by:user.id,owner_id:user.id}).select('id,starts_at,ends_at,venue,city,work_position,technician_id,booking_status,technician_response,artists(name)').single();if(r.error)return toast(r.error.message);const sent=await sendTechnicianEmail(r.data,true);q('concertDialog').close();form.reset();const reserved=document.querySelector('input[name="concertBookingStatus"][value="reserved"]');if(reserved)reserved.checked=true;toast(sent?'Data criada e convite enviado por e-mail.':'Data criada, mas o e-mail não foi enviado.');await loadAll()}}
function refresh(){injectFields();fillTechnicians();patchSubmit();decorate()}
function patchLoadAll(){if(window.__teamDuckLoadPatched||typeof window.loadAll!=='function')return;const original=window.loadAll;window.loadAll=async function(...args){const out=await original.apply(this,args);requestAnimationFrame(refresh);return out};window.__teamDuckLoadPatched=true}
addEventListener('load',()=>{patchLoadAll();setTimeout(refresh,250);setTimeout(refresh,1000)});
})();