(()=>{
const q=id=>document.getElementById(id);
function effRole(){try{return window.TeamDuckRoleLayout?.effectiveRole?.()||me?.role||null}catch(_){return me?.role||null}}
function preview(){try{return me?.role==='admin'&&['partner','substitute'].includes(sessionStorage.getItem('team-duck-role-preview'))}catch(_){return false}}
function nextSunday(){const d=new Date();d.setHours(0,0,0,0);const days=(7-d.getDay())%7||7;d.setDate(d.getDate()+days);return d}
function sundayAfter(s){const d=new Date(s);d.setDate(d.getDate()+7);d.setHours(23,59,59,999);return d}
function monthEnd(){const d=new Date();d.setMonth(d.getMonth()+1);return d}
function partnerAmount(c){const total=Math.max(0,Number(c.fee_override||0)),sub=!!c.substitute_technician_id,subFee=Math.max(0,Number(c.substitute_fee||0));return sub?Math.max(0,Number(c.principal_commission??(total-subFee))):total}
function card(c){const role=effRole();let amount='';if(role==='admin')amount=`<span class="money">${money(c.fee_override)}</span>`;else if(role==='partner')amount=`<span class="money">${money(partnerAmount(c))}</span>`;return `<article class="item clickable" data-dash-concert="${c.id}"><div><strong>${esc(c.artists?.name||'Trabalho')}</strong><small>${dt(c.starts_at)} · ${esc(c.city||c.venue||'Local por definir')} · ${esc(c.work_position||'')}</small></div>${amount}</article>`}
function wire(host){host?.querySelectorAll('[data-dash-concert]').forEach(el=>el.onclick=()=>window.openConcertView?.(el.dataset.dashConcert))}
function renderWindows(){const w=q('nextWeekConcerts'),m=q('nextMonthConcerts'),count=q('nextMonthCount');if(!w||!m)return;if(preview()){w.innerHTML='<div class="empty">Sem trabalhos nesta pré-visualização.</div>';m.innerHTML='<div class="empty">Sem trabalhos nesta pré-visualização.</div>';if(count)count.textContent='0';return}const ws=nextSunday(),we=sundayAfter(ws),now=new Date(),me=monthEnd();const week=(concerts||[]).filter(c=>{const d=new Date(c.starts_at);return d>=ws&&d<=we&&!c.closed});const month=(concerts||[]).filter(c=>{const d=new Date(c.starts_at);return d>=now&&d<=me&&!c.closed});w.innerHTML=week.map(card).join('')||'<div class="empty">Sem trabalhos na próxima semana.</div>';m.innerHTML=month.map(card).join('')||'<div class="empty">Sem trabalhos no próximo mês.</div>';if(count)count.textContent=month.length;wire(w);wire(m)}
function patch(){if(window.__dashboardWindowsPatched||typeof window.loadAll!=='function')return;const original=window.loadAll;window.loadAll=async function(...args){const out=await original.apply(this,args);requestAnimationFrame(renderWindows);return out};window.__dashboardWindowsPatched=true}
addEventListener('load',()=>{patch();setTimeout(renderWindows,300);setTimeout(renderWindows,1200)});window.TeamDuckDashboardWindows={refresh:renderWindows};
})();