(()=>{
const KEY='team-duck-demo-mode',PREVIEW='team-duck-role-preview';let snapshot=null,renderTimer=null;
const q=id=>document.getElementById(id),fmt=v=>new Intl.DateTimeFormat('pt-PT',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)),eur=v=>new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format(v);
const names=['Miguel Santos','Ana Martins','Tiago Lopes','Marta Ferreira','Bruno Costa','Inês Almeida'],cities=['Lisboa','Porto','Braga','Coimbra','Aveiro','Faro'];
const bands=['Neon Harbor','Atlas Avenue','Lunar Echo','Velvet Transit','Northline','Golden Pulse'];
const now=()=>new Date();function at(days,hour=21,min=30){const d=now();d.setDate(d.getDate()+days);d.setHours(hour,min,0,0);return d.toISOString()}
function fakeData(){const t=names.map((n,i)=>({id:`demo-tech-${i+1}`,full_name:n,email:`demo${i+1}@example.invalid`,role:i<3?'partner':'substitute',active:true,base_city:cities[i],phone:'+351 000 000 000',nif:'000000000',permissions:{artists_manage:true,files_manage:true,concerts_manage:true,financials_view:i<3},photo_path:null}));const a=bands.map((n,i)=>({id:`demo-artist-${i+1}`,name:n,base_fee:[850,1200,1500,950,1800,1100][i],contact_email:`booking${i+1}@example.invalid`,contact_phone:'+351 000 000 000',created_by:t[i%3].id,principal_technician_id:t[i%3].id}));const c=[
[-20,0,0,'Lisboa','Altice Arena','FOH',850],[-12,1,1,'Porto','Super Bock Arena','ROH',1200],[-3,2,2,'Braga','Forum Braga','FOH+ROH',1500],[2,3,0,'Coimbra','Convento São Francisco','FOH',950],[5,4,1,'Aveiro','Centro Congressos','ROH',1800],[5,5,2,'Aveiro','Teatro Aveirense','FOH',1100],[9,0,3,'Faro','Teatro das Figuras','FOH+ROH',1000],[14,1,4,'Lisboa','Campo Pequeno','FOH',1300],[14,2,5,'Lisboa','Coliseu','ROH',1550],[21,3,0,'Porto','Casa da Música','FOH',900],[30,4,1,'Braga','Theatro Circo','FOH+ROH',1750],[45,5,2,'Coimbra','TAGV','ROH',1150]
].map((x,i)=>({id:`demo-concert-${i+1}`,artist_id:a[x[1]].id,artists:{name:a[x[1]].name},starts_at:at(x[0],i%2?20:21,i%3?30:0),ends_at:at(x[0]+(i===5?0:1),1,0),city:x[3],venue:x[4],work_position:x[5],fee_override:x[6],amount_received:i%3===0?x[6]:Math.round(x[6]*.4),status:'confirmed',closed:x[0]<-7,principal_technician_id:t[x[2]].id,technician_id:t[x[2]].id,substitute_technician_id:i>=6&&i%2===0?t[(x[2]+3)%6].id:null,owner_id:t[x[2]].id}));return{team:t,artists:a,concerts:c}}
function isDemo(){return sessionStorage.getItem(KEY)==='1'}
function actualRole(){try{return me?.role||null}catch(_){return null}}
function saveSnapshot(){if(snapshot)return;try{snapshot={artists:[...(artists||[])],concerts:[...(concerts||[])],team:[...(team||[])],me:me?{...me}:me}}catch(_){}}
function useFakeGlobals(){saveSnapshot();const f=fakeData();try{artists=f.artists;concerts=f.concerts;team=f.team}catch(_){}return f}
function restore(){if(!snapshot)return;try{artists=snapshot.artists;concerts=snapshot.concerts;team=snapshot.team}catch(_){}snapshot=null}
function banner(){let b=q('tdDemoBanner');if(!b){b=document.createElement('div');b.id='tdDemoBanner';b.textContent='MODO DEMONSTRAÇÃO · DADOS 100% FICTÍCIOS · NENHUMA ALTERAÇÃO É GRAVADA';b.style.cssText='position:sticky;top:0;z-index:999;background:#d8ff3e;color:#07130b;padding:8px 12px;text-align:center;font-size:12px;font-weight:950;letter-spacing:.04em;border-bottom:1px solid rgba(0,0,0,.25)';q('app')?.prepend(b)}b.classList.toggle('hidden',!isDemo())}
function selector(){const wrap=q('rolePreviewControl');if(!wrap)return;wrap.classList.remove('hidden');wrap.style.cssText='display:flex!important;align-items:center;margin-left:auto;margin-right:8px';let s=q('rolePreviewSelect');if(!s){s=document.createElement('select');s.id='rolePreviewSelect';wrap.appendChild(s)}const r=actualRole();const options=r==='admin'?[['demo','Demonstração'],['admin','Administrador'],['partner','Parceiro'],['substitute','Substituto']]:[['demo','Demonstração'],['real',r==='partner'?'Minha vista · Parceiro':'Minha vista · Substituto']];s.innerHTML=options.map(([v,l])=>`<option value="${v}">${l}</option>`).join('');s.value=isDemo()?'demo':(r==='admin'?(sessionStorage.getItem(PREVIEW)||'admin'):'real');s.onchange=()=>{const v=s.value;if(v==='demo'){sessionStorage.setItem(KEY,'1');if(r==='admin')sessionStorage.removeItem(PREVIEW)}else{sessionStorage.removeItem(KEY);if(r==='admin'){if(v==='admin')sessionStorage.removeItem(PREVIEW);else sessionStorage.setItem(PREVIEW,v)}}location.reload()}}
function card(c,f){const past=new Date(c.ends_at||c.starts_at).getTime()<Date.now(),color=past?'#7d8580':['#54d96b','#f2b72f','#38a9e8','#9b6cff','#ff6b57','#2fd0b2'][bands.indexOf(c.artists.name)%6];return `<article class="item td-demo-card" style="--artist-color:${color};${past?'filter:grayscale(1);opacity:.68':''}"><div><strong>${c.artists.name}</strong><small>${fmt(c.starts_at)} · ${c.city} · ${c.work_position} · ${names[(c.principal_technician_id||'').split('-').pop()-1]||'Técnico Demo'}</small></div>${f?`<span class="money">${eur(c.fee_override)}</span>`:''}</article>`}
function renderDemo(){if(!isDemo())return;const f=useFakeGlobals();document.body.dataset.demoMode='1';banner();selector();const who=q('whoami');if(who)who.textContent='Team Duck · Demonstração fictícia';const future=f.concerts.filter(c=>new Date(c.starts_at)>=new Date());if(q('statConcerts'))q('statConcerts').textContent=String(future.length);if(q('statArtists'))q('statArtists').textContent=String(f.artists.length);if(q('statDue'))q('statDue').textContent=eur(f.concerts.reduce((s,c)=>s+Math.max(0,c.fee_override-c.amount_received),0));if(q('nextConcerts'))q('nextConcerts').innerHTML=future.slice(0,5).map(c=>card(c,true)).join('');if(q('concerts'))q('concerts').innerHTML=f.concerts.map(c=>card(c,true)).join('');if(q('closedConcerts'))q('closedConcerts').innerHTML=f.concerts.filter(c=>c.closed).map(c=>card(c,true)).join('')||'<div class="empty">Sem trabalhos fechados.</div>';if(q('artistList'))q('artistList').innerHTML=f.artists.map(a=>`<article class="item"><div><strong>${a.name}</strong><small>${a.contact_email} · Cachet demo ${eur(a.base_fee)}</small></div><button type="button" class="secondary tiny" data-demo-action>Ficheiros</button></article>`).join('');if(q('teamList'))q('teamList').innerHTML=f.team.map((p,i)=>`<article class="item"><div><strong>${p.full_name}</strong><small>${p.base_city} · ${i<3?'Parceiro':'Substituto'} · ativo</small></div><span class="td-demo-status ${i===3?'busy':i===4?'hold':'free'}">${i===3?'Ocupado':i===4?'Reserva':'Livre'}</span></article>`).join('');q('newMember')?.classList.remove('hidden');q('newArtist')?.classList.remove('hidden');q('newConcert')?.classList.remove('hidden');document.querySelectorAll('#nav button').forEach(b=>b.classList.remove('hidden'));window.TeamDuckCompactAgenda?.refresh?.();}
function blockWrites(){document.addEventListener('submit',e=>{if(!isDemo())return;e.preventDefault();e.stopImmediatePropagation();toast('Modo demonstração: alteração simulada. Nada foi gravado.')},true);document.addEventListener('click',e=>{if(!isDemo())return;const t=e.target.closest('[data-deletefile],[data-demo-action],#copyInvite,#shareInvite');if(t){e.preventDefault();e.stopImmediatePropagation();toast('Modo demonstração: esta ação é apenas ilustrativa.')}},true)}
function schedule(ms=80){clearTimeout(renderTimer);renderTimer=setTimeout(()=>{selector();banner();if(isDemo())renderDemo()},ms)}
function boot(){blockWrites();let tries=0;const ready=()=>{tries++;if(!q('app')||!actualRole()){if(tries<60)return setTimeout(ready,100);return}if(actualRole()==='admin'&&sessionStorage.getItem(KEY)===null&&sessionStorage.getItem(PREVIEW)===null)sessionStorage.setItem(KEY,'1');selector();banner();if(isDemo())renderDemo();document.addEventListener('click',e=>{if(e.target.closest('#nav button'))schedule(50)},{passive:true});if(typeof window.loadAll==='function'&&!window.__demoLoadPatched){const old=window.loadAll;window.loadAll=async function(...args){const r=await old.apply(this,args);schedule(60);return r};window.__demoLoadPatched=true}};ready()}
const st=document.createElement('style');st.textContent='body[data-demo-mode="1"] #rolePreviewNotice{display:none!important}.td-demo-status{font-size:12px;font-weight:900;padding:6px 9px;border-radius:999px}.td-demo-status.free{background:#183d25;color:#72ee91}.td-demo-status.hold{background:#443813;color:#ffd45f}.td-demo-status.busy{background:#4b1c1c;color:#ff7b7b}';document.head.appendChild(st);
if(document.readyState==='loading')addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.TeamDuckDemo={isDemo,refresh:()=>schedule(0),exit:()=>{sessionStorage.removeItem(KEY);restore();location.reload()}};
})();