(()=>{
const q=id=>document.getElementById(id);
function effRole(){try{return window.TeamDuckRoleLayout?.effectiveRole?.()||me?.role||null}catch(_){return me?.role||null}}
function preview(){try{return me?.role==='admin'&&['partner','substitute'].includes(sessionStorage.getItem('team-duck-role-preview'))}catch(_){return false}}
function ownedByPartner(c){const uid=String(me?.id||'');return !!uid&&String(c?.principal_technician_id||c?.owner_id||c?.created_by||'')===uid}
function scopedConcerts(){return effRole()==='partner'?(concerts||[]).filter(ownedByPartner):(concerts||[])}
function grossFor(c,personId){const total=Math.max(0,Number(c.fee_override||0)),principal=String(c.principal_technician_id||c.owner_id||''),sub=String(c.substitute_technician_id||''),pid=String(personId),subFee=sub?Math.max(0,Number(c.substitute_fee||0)):0,principalPart=sub?Math.max(0,Number(c.principal_commission??(total-subFee))):total;if(pid===principal)return principalPart;if(sub&&pid===sub)return subFee;return 0}
function dueFor(person){return scopedConcerts().filter(c=>!c.closed).reduce((sum,c)=>{const total=Math.max(0,Number(c.fee_override||0));if(!total)return sum;const outstanding=Math.max(0,total-Number(c.amount_received||0));if(!outstanding)return sum;return sum+grossFor(c,person.id)*(outstanding/total)},0)}
function partnerPeople(){if(preview())return[];const ids=new Set([String(me?.id||'')]);scopedConcerts().forEach(c=>{if(c.substitute_technician_id)ids.add(String(c.substitute_technician_id))});return (team||[]).filter(p=>ids.has(String(p.id)))}
function render(){const host=q('dueByPerson');if(!host||!me)return;const title=host.previousElementSibling,role=effRole();if(role==='substitute'){host.classList.add('hidden');if(title)title.classList.add('hidden');return}host.classList.remove('hidden');if(title)title.classList.remove('hidden');let people=[];if(role==='admin')people=(team||[]).filter(p=>p.active!==false);else if(role==='partner')people=partnerPeople();if(role==='partner'&&title)title.textContent='Por receber · Eu e os meus substitutos';host.innerHTML=people.map(p=>`<article class="item"><div><strong>${esc(p.full_name||p.email||'Membro')}</strong><small>${String(p.id)===String(me?.id)?'Principal':'Substituto'}</small></div><span class="money">${money(dueFor(p))}</span></article>`).join('')||'<div class="empty">Sem valores a receber.</div>'}
if(!window.__financeSplitPatched&&typeof window.loadAll==='function'){const original=window.loadAll;window.loadAll=async function(...args){const out=await original.apply(this,args);setTimeout(render,0);return out};window.__financeSplitPatched=true}
window.TeamDuckFinance={refresh:render,dueFor,grossFor,scopedConcerts};render();setTimeout(render,350);setTimeout(render,1200);
})();