(()=>{
const q=id=>document.getElementById(id),norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
function make(id,placeholder,oninput){let w=q(id);if(w)return w;w=document.createElement('div');w.id=id;w.className='td-quick-search';w.innerHTML=`<span aria-hidden="true">🔎</span><input type="search" placeholder="${placeholder}" autocomplete="off" aria-label="${placeholder}">`;w.querySelector('input').addEventListener('input',e=>oninput(norm(e.target.value)));return w}
function filterCards(hostId,term){const host=q(hostId);if(!host)return;[...host.querySelectorAll(':scope > .item')].forEach(card=>{const text=norm(card.querySelector('strong')?.textContent||card.textContent);card.style.display=!term||text.includes(term)?'':'none'})}
function teamSearch(){const page=q('team'),list=q('teamList');if(!page||!list)return;const title=page.querySelector('.title-row');if(!title)return;const w=make('tdTeamSearch','Pesquisar técnico…',t=>filterCards('teamList',t));if(!w.isConnected)title.insertAdjacentElement('afterend',w)}
function artistSearch(){const page=q('artists'),list=q('artistList');if(!page||!list)return;const title=page.querySelector('.title-row');if(!title)return;const w=make('tdArtistSearch','Pesquisar artista…',t=>filterCards('artistList',t));if(!w.isConnected)title.insertAdjacentElement('afterend',w)}
function substituteSearch(){const page=q('agenda'),members=q('agendaMembers');if(!page||!members)return;let w=q('tdSubAgendaSearch');if(!w){w=make('tdSubAgendaSearch','Pesquisar substituto…',term=>{const people=(team||[]).filter(p=>p.active!==false&&norm(p.full_name||p.email).includes(term));const match=term&&people[0];if(!term){window.TeamDuckAgendaMembers?.refresh?.();return}if(match){const btn=[...members.querySelectorAll('button')].find(b=>norm(b.textContent).includes(norm(match.full_name||match.email)));if(btn){btn.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'});btn.click()}}});}const controls=page.querySelector('.td-agenda-view-controls,.agenda-view-controls,[data-agenda-view-controls]')||members;if(w.parentElement!==controls.parentElement)controls.insertAdjacentElement('beforebegin',w)}
function style(){if(q('tdGlobalSearchStyle'))return;const s=document.createElement('style');s.id='tdGlobalSearchStyle';s.textContent='.td-quick-search{display:flex;align-items:center;gap:8px;margin:0 0 12px;padding:8px 11px;border:1px solid rgba(255,255,255,.15);border-radius:12px;background:rgba(5,18,10,.55);backdrop-filter:blur(8px)}.td-quick-search input{width:100%;margin:0!important;border:0!important;outline:0;background:transparent!important;color:inherit;font:inherit}.td-quick-search input::placeholder{color:rgba(255,255,255,.62)}';document.head.appendChild(s)}
function scan(){style();teamSearch();artistSearch();substituteSearch()}
function boot(){scan();document.querySelectorAll('#nav button').forEach(b=>b.addEventListener('click',()=>setTimeout(scan,80)));if(typeof loadAll==='function'&&!window.__globalSearchLoadPatched){const old=loadAll;loadAll=async function(...a){const r=await old.apply(this,a);setTimeout(scan,80);return r};window.__globalSearchLoadPatched=true}new MutationObserver(()=>setTimeout(scan,50)).observe(q('app')||document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.TeamDuckGlobalSearch={scan};
})();