(()=>{
const KEY='team-duck-language';
const langs={pt:{label:'PT',html:'pt-PT'},en:{label:'EN',html:'en'},fr:{label:'FR',html:'fr'}};
const dict={
'Entrar':{en:'Sign in',fr:'Connexion'},'E-mail':{en:'Email',fr:'E-mail'},'Password':{en:'Password',fr:'Mot de passe'},'Confirmar password':{en:'Confirm password',fr:'Confirmer le mot de passe'},'Criar credenciais':{en:'Create credentials',fr:'Créer les identifiants'},'Nome completo':{en:'Full name',fr:'Nom complet'},'Telefone':{en:'Phone',fr:'Téléphone'},'NIF':{en:'Tax ID',fr:'NIF'},'CC / identificação':{en:'ID / identification',fr:'CNI / identification'},'Ativar conta':{en:'Activate account',fr:'Activer le compte'},
'Sair':{en:'Sign out',fr:'Déconnexion'},'Resumo':{en:'Overview',fr:'Résumé'},'Agenda':{en:'Schedule',fr:'Agenda'},'Substitutos':{en:'Substitutes',fr:'Remplaçants'},'Fechados':{en:'Completed',fr:'Terminés'},'Finalizados':{en:'Completed',fr:'Finalisés'},'Artistas':{en:'Artists',fr:'Artistes'},'Equipa':{en:'Team',fr:'Équipe'},'Próximos trabalhos':{en:'Upcoming jobs',fr:'Prochains travaux'},'Próxima semana':{en:'Next week',fr:'Semaine prochaine'},'Próximo mês':{en:'Next month',fr:'Mois prochain'},'Domingo a domingo':{en:'Sunday to Sunday',fr:'Du dimanche au dimanche'},'De hoje até à mesma data do próximo mês':{en:'From today until the same date next month',fr:"D’aujourd’hui à la même date le mois prochain"},'Por receber':{en:'Outstanding',fr:'À recevoir'},'Por receber · Equipa':{en:'Outstanding · Team',fr:'À recevoir · Équipe'},
'+ Trabalho':{en:'+ Job',fr:'+ Travail'},'+ Artista':{en:'+ Artist',fr:'+ Artiste'},'+ Convidar':{en:'+ Invite',fr:'+ Inviter'},'Trabalhos finalizados e pagos.':{en:'Completed and paid jobs.',fr:'Travaux finalisés et payés.'},'Convites':{en:'Invitations',fr:'Invitations'},'Novo artista':{en:'New artist',fr:'Nouvel artiste'},'Cachet base (€)':{en:'Base fee (€)',fr:'Cachet de base (€)'},'Notas':{en:'Notes',fr:'Notes'},'Cancelar':{en:'Cancel',fr:'Annuler'},'Guardar':{en:'Save',fr:'Enregistrer'},'Ficheiros':{en:'Files',fr:'Fichiers'},'Fechar':{en:'Close',fr:'Fermer'},'Rider técnico':{en:'Technical rider',fr:'Fiche technique'},'Áudio / Concerto':{en:'Audio / Concert',fr:'Audio / Concert'},'Imagem':{en:'Image',fr:'Image'},'Documento':{en:'Document',fr:'Document'},'Outro':{en:'Other',fr:'Autre'},'Adicionar ficheiro':{en:'Add file',fr:'Ajouter un fichier'},
'Convidar membro':{en:'Invite member',fr:'Inviter un membre'},'A pessoa recebe um link e cria as próprias credenciais.':{en:'The person receives a link and creates their own credentials.',fr:'La personne reçoit un lien et crée ses propres identifiants.'},'Função':{en:'Role',fr:'Rôle'},'Parceiro':{en:'Partner',fr:'Partenaire'},'Substituto':{en:'Substitute',fr:'Remplaçant'},'Administrador':{en:'Administrator',fr:'Administrateur'},'Permissões':{en:'Permissions',fr:'Autorisations'},'Criar link':{en:'Create link',fr:'Créer le lien'},'Convite criado':{en:'Invitation created',fr:'Invitation créée'},'Envia este link à pessoa:':{en:'Send this link to the person:',fr:'Envoyez ce lien à la personne :'},'Copiar':{en:'Copy',fr:'Copier'},'Partilhar':{en:'Share',fr:'Partager'},
'Editar membro':{en:'Edit member',fr:'Modifier le membre'},'Conta ativa':{en:'Active account',fr:'Compte actif'},'Documentação':{en:'Documents',fr:'Documentation'},'Novo trabalho':{en:'New job',fr:'Nouveau travail'},'Artista':{en:'Artist',fr:'Artiste'},'Início':{en:'Start',fr:'Début'},'Fim':{en:'End',fr:'Fin'},'Local':{en:'Venue',fr:'Lieu'},'Cidade':{en:'City',fr:'Ville'},'Cachet (€)':{en:'Fee (€)',fr:'Cachet (€)'},'Recebido (€)':{en:'Received (€)',fr:'Reçu (€)'},
'Demonstração':{en:'Demo',fr:'Démonstration'},'Minha vista · Parceiro':{en:'My view · Partner',fr:'Ma vue · Partenaire'},'Minha vista · Substituto':{en:'My view · Substitute',fr:'Ma vue · Remplaçant'},'A minha ficha':{en:'My profile',fr:'Ma fiche'},'Cidade base por definir':{en:'Base city not set',fr:'Ville de base non définie'},'Livre':{en:'Available',fr:'Libre'},'Reserva':{en:'Hold',fr:'Réserve'},'Ocupado':{en:'Busy',fr:'Occupé'},'Pago':{en:'Paid',fr:'Payé'},'PAGO':{en:'PAID',fr:'PAYÉ'},
'MODO DEMONSTRAÇÃO · DADOS 100% FICTÍCIOS · NENHUMA ALTERAÇÃO É GRAVADA':{en:'DEMO MODE · 100% FICTIONAL DATA · NO CHANGES ARE SAVED',fr:'MODE DÉMONSTRATION · DONNÉES 100 % FICTIVES · AUCUNE MODIFICATION N’EST ENREGISTRÉE'},'Team Duck · Demonstração fictícia':{en:'Team Duck · Fictional demo',fr:'Team Duck · Démonstration fictive'},'Modo demonstração: alteração simulada. Nada foi gravado.':{en:'Demo mode: simulated change. Nothing was saved.',fr:'Mode démonstration : modification simulée. Rien n’a été enregistré.'}
};
let current=localStorage.getItem(KEY)||'pt';if(!langs[current])current='pt';
const originalText=new WeakMap(),originalPlaceholder=new WeakMap(),originalTitle=new WeakMap();
function translateString(s,lang){if(lang==='pt')return s;const trimmed=s.trim(),hit=dict[trimmed];if(hit?.[lang])return s.replace(trimmed,hit[lang]);let out=s;for(const [pt,v] of Object.entries(dict)){if(v[lang]&&out.includes(pt))out=out.split(pt).join(v[lang])}return out}
function translateNode(n,lang){if(n.nodeType!==3)return;const p=n.parentElement;if(!p||['SCRIPT','STYLE','OPTION'].includes(p.tagName))return;const t=n.nodeValue;if(!t?.trim())return;if(!originalText.has(n))originalText.set(n,t);n.nodeValue=lang==='pt'?originalText.get(n):translateString(originalText.get(n),lang)}
function translateElement(el,lang){if(!(el instanceof Element))return;for(const n of el.childNodes)if(n.nodeType===3)translateNode(n,lang);if(el.matches('input,textarea')){if(!originalPlaceholder.has(el))originalPlaceholder.set(el,el.placeholder||'');const o=originalPlaceholder.get(el);if(o)el.placeholder=lang==='pt'?o:translateString(o,lang)}if(el.hasAttribute('title')){if(!originalTitle.has(el))originalTitle.set(el,el.title);const o=originalTitle.get(el);el.title=lang==='pt'?o:translateString(o,lang)}el.querySelectorAll('*').forEach(x=>{for(const n of x.childNodes)if(n.nodeType===3)translateNode(n,lang);if(x.matches('input,textarea')){if(!originalPlaceholder.has(x))originalPlaceholder.set(x,x.placeholder||'');const o=originalPlaceholder.get(x);if(o)x.placeholder=lang==='pt'?o:translateString(o,lang)}})}
function buildSelector(){let host=document.getElementById('tdLanguage');if(!host){host=document.createElement('div');host.id='tdLanguage';host.className='td-language';host.innerHTML='<button type="button" data-lang="pt">PT</button><span>·</span><button type="button" data-lang="en">EN</button><span>·</span><button type="button" data-lang="fr">FR</button>';const header=document.querySelector('#app > header');if(header){const view=document.getElementById('rolePreviewControl');header.insertBefore(host,view||document.getElementById('logout')||null)}else{const login=document.querySelector('#login .login-card');if(login)login.prepend(host)}host.addEventListener('click',e=>{const b=e.target.closest('[data-lang]');if(b)setLanguage(b.dataset.lang)})}host.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===current));return host}
function ensureSelectors(){buildSelector();const login=document.querySelector('#login .login-card');if(login&&!login.querySelector('#tdLanguageLogin')){const h=document.createElement('div');h.id='tdLanguageLogin';h.className='td-language td-language-login';h.innerHTML='<button type="button" data-lang="pt">PT</button><span>·</span><button type="button" data-lang="en">EN</button><span>·</span><button type="button" data-lang="fr">FR</button>';h.onclick=e=>{const b=e.target.closest('[data-lang]');if(b)setLanguage(b.dataset.lang)};login.prepend(h)}document.querySelectorAll('.td-language [data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===current))}
function apply(lang=current){document.documentElement.lang=langs[lang].html;translateElement(document.body,lang);ensureSelectors();document.dispatchEvent(new CustomEvent('teamduck:language',{detail:{language:lang}}))}
function setLanguage(lang){if(!langs[lang])return;current=lang;localStorage.setItem(KEY,lang);apply(lang)}
let mo;function boot(){ensureSelectors();apply(current);mo=new MutationObserver(ms=>{for(const m of ms)for(const n of m.addedNodes)if(n.nodeType===1)translateElement(n,current);ensureSelectors()});mo.observe(document.body,{childList:true,subtree:true});const st=document.createElement('style');st.textContent='.td-language{display:flex;align-items:center;gap:4px;flex:0 0 auto;margin-right:9px;padding:4px 7px;border:1px solid rgba(255,255,255,.12);border-radius:999px;background:rgba(4,13,8,.45);backdrop-filter:blur(8px)}.td-language button{appearance:none;border:0!important;background:transparent!important;color:#929b95!important;padding:2px 3px!important;margin:0!important;min-width:0!important;font-size:11px!important;font-weight:850!important;letter-spacing:.04em;box-shadow:none!important}.td-language button.active{color:#d8ff3e!important}.td-language span{color:rgba(255,255,255,.2);font-size:10px}.td-language-login{position:absolute;top:12px;right:12px;margin:0}.login-card{position:relative}@media(max-width:600px){.td-language{gap:2px;padding:3px 5px;margin-right:5px}.td-language button{font-size:10px!important}}';document.head.appendChild(st)}
if(document.readyState==='loading')addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.TeamDuckLanguage={get:()=>current,set:setLanguage,apply:()=>apply(current),t:s=>translateString(s,current)};
})();