(()=>{
const q=id=>document.getElementById(id),photoCache=new Map();
const getMe=()=>{try{return me||null}catch(_){return null}},getTeam=()=>{try{return Array.isArray(team)?team:[]}catch(_){return[]}},getConcerts=()=>{try{return Array.isArray(concerts)?concerts:[]}catch(_){return[]}};
const partnerId=()=>String(getMe()?.id||''),isPartner=()=>getMe()?.role==='partner',isAdmin=()=>getMe()?.role==='admin';
const ownMember=p=>isPartner()&&String(p?.owner_partner_id||'')===partnerId();
async function signed(p){if(!p?.photo_path)return '401FB0DA-DAD2-49CE-89E0-A9850A0722F7.png';if(photoCache.has(p.photo_path))return photoCache.get(p.photo_path);const r=await sb.storage.from('team-images').createSignedUrl(p.photo_path,3600);const u=r.error?'401FB0DA-DAD2-49CE-89E0-A9850A0722F7.png':r.data.signedUrl;photoCache.set(p.photo_path,u);return u}
function teamNav(){return [...document.querySelectorAll('#nav button')].find(b=>b.dataset.page==='team')||null}
function preparePartnerUi(){if(!isPartner())return;teamNav()?.classList.remove('hidden');q('team')?.classList.remove('hidden');q('newMember')?.classList.remove('hidden');q('inviteDialog')?.classList.remove('hidden');q('inviteLinkDialog')?.classList.remove('hidden');q('memberDialog')?.classList.add('hidden');const h=q('team')?.querySelector('h2');if(h)h.textContent='A minha equipa';const inviteTitle=q('inviteForm')?.querySelector('h3');if(inviteTitle)inviteTitle.textContent='Convidar substituto';const roleLabel=q('inviteRole')?.closest('label');if(roleLabel)roleLabel.classList.add('hidden');const fs=q('inviteForm')?.querySelector('fieldset');if(fs)fs.classList.add('hidden');if(q('inviteRole'))q('inviteRole').value='substitute';q('newMember').onclick=()=>{if(q('inviteRole'))q('inviteRole').value='substitute';q('inviteDialog')?.showModal()}}
async function renderPartnerTeam(){if(!isPartner())return;preparePartnerUi();const host=q('teamList');if(!host)return;const rows=getTeam().filter(ownMember).sort((a,b)=>String(a.full_name||a.email||'').localeCompare(String(b.full_name||b.email||''),'pt'));host.innerHTML='';for(const p of rows){const u=await signed(p),card=document.createElement('article');card.className='item';card.innerHTML=`<div class="td-partner-member"><img src="${u}" alt=""><div><strong>${esc(p.full_name||p.email||'Substituto')}</strong><small>${esc(p.base_city||'Cidade base por definir')} · Substituto${p.active===false?' · inativo':''}</small></div></div>`;card.querySelector('img').onclick=e=>{e.stopPropagation();window.TeamDuckImages?.showPersonPhoto?.(p)};host.appendChild(card)}if(!rows.length)host.innerHTML='<div class="empty">Ainda não adicionaste substitutos à tua equipa.</div>';const inviteList=q('inviteList');if(inviteList&&!inviteList.dataset.partnerOwned){inviteList.dataset.partnerOwned='1';inviteList.innerHTML='<div class="muted">Os convites criados por ti ficam ligados à tua equipa e continuam sujeitos à validação do administrador.</div>'}}
function adminLabels(){if(!isAdmin())return;const rows=getTeam();for(const p of rows){if(!p.owner_partner_id)continue;const owner=rows.find(x=>String(x.id)===String(p.owner_partner_id)),card=document.querySelector(`[data-member="${p.id}"]`);if(!card||card.querySelector('[data-owner-partner]'))continue;const small=card.querySelector('small');if(!small)continue;const tag=document.createElement('span');tag.dataset.ownerPartner='1';tag.textContent=` · Equipa de ${owner?.full_name||owner?.email||'Parceiro'}`;small.appendChild(tag)}}
function availabilityState(personId,targetStart,excludeId=''){const same=getConcerts().filter(c=>String(c.id)!==String(excludeId)&&c.status!=='cancelled'&&[c.technician_id,c.principal_technician_id,c.substitute_technician_id].some(x=>String(x||'')===String(personId))&&new Date(c.starts_at).toDateString()===new Date(targetStart).toDateString());if(!same.length)return 0;return same.some(c=>(c.booking_status||c.status)==='confirmed'&&c.booking_status!=='reserved')?2:1}
function rowPerson(row){const id=row.dataset.techId;if(id)return getTeam().find(p=>String(p.id)===String(id));const name=row.querySelector('b')?.textContent?.trim();return getTeam().find(p=>String(p.full_name||p.email||'').trim()===name)||null}
function reorderAvailability(host){if(!isPartner()||!host)return;const rows=[...host.querySelectorAll('.td-avail-row')];if(rows.length<2)return;rows.sort((a,b)=>{const pa=rowPerson(a),pb=rowPerson(b),oa=ownMember(pa)?0:1,ob=ownMember(pb)?0:1;if(oa!==ob)return oa-ob;const rank=r=>r.classList.contains('td-avail-free')?0:r.classList.contains('td-avail-reserved')?1:2,ra=rank(a),rb=rank(b);if(ra!==rb)return ra-rb;return String(pa?.full_name||'').localeCompare(String(pb?.full_name||''),'pt')});rows.forEach(r=>host.appendChild(r));rows.forEach(r=>{const p=rowPerson(r);if(!p)return;let badge=r.querySelector('[data-own-team]');if(ownMember(p)&&!badge){badge=document.createElement('em');badge.dataset.ownTeam='1';badge.textContent='Minha equipa';badge.className='td-own-team';r.querySelector('span')?.appendChild(badge)}else if(!ownMember(p))badge?.remove()})}
async function decorateSubstituteAgenda(){if(!isPartner())return;const active=document.querySelector('#nav button[data-agenda-filter="SUB"].active');if(!active)return;for(const card of document.querySelectorAll('#concerts>.item[data-concert-id]')){const c=getConcerts().find(x=>String(x.id)===String(card.dataset.concertId));if(!c?.substitute_technician_id)continue;const p=getTeam().find(x=>String(x.id)===String(c.substitute_technician_id));if(!p)continue;const img=card.querySelector('.td-compact-avatar'),line=card.querySelector('.td-tech-line');if(img){img.src=await signed(p);img.style.visibility='visible';img.onclick=e=>{e.stopPropagation();window.TeamDuckImages?.showPersonPhoto?.(p)}}if(line)line.textContent=`${p.full_name||p.email||'Substituto'}${p.base_city?' · '+p.base_city:''}`}}
function scheduleDecorate(){setTimeout(()=>{renderPartnerTeam();adminLabels();reorderAvailability(q('substituteAvailability'));reorderAvailability(q('tdAvailabilityChoices'));decorateSubstituteAgenda()},180)}
function wireInvite(){const f=q('inviteForm');if(!f||f.dataset.partnerTeamWired)return;f.dataset.partnerTeamWired='1';const original=f.onsubmit;f.onsubmit=async e=>{if(!isPartner())return original?.call(f,e);e.preventDefault();const email=q('inviteMemberEmail')?.value.trim();if(!email)return;const r=await sb.functions.invoke('create-team-invite',{body:{email,role:'substitute',permissions:{}}});if(r.error||!r.data?.ok)return toast(r.data?.error||r.error?.message||'Erro ao criar convite');const link=`${location.origin}${location.pathname}?invite=${encodeURIComponent(r.data.invitation.token)}`;q('inviteDialog')?.close();q('inviteLink').value=link;q('inviteLinkDialog')?.showModal();f.reset();if(q('inviteRole'))q('inviteRole').value='substitute';toast('Convite criado para a tua equipa.')}}
function boot(){wireInvite();scheduleDecorate();document.addEventListener('click',e=>{if(e.target.closest('#nav button[data-page="team"],#nav button[data-agenda-filter="SUB"],#newMember,[data-dual-action]'))scheduleDecorate()},{passive:true});['substituteAvailability','tdAvailabilityChoices'].forEach(id=>{const h=q(id);if(h&&!h.dataset.partnerTeamObserved){h.dataset.partnerTeamObserved='1';new MutationObserver(()=>{clearTimeout(h._ptTimer);h._ptTimer=setTimeout(()=>reorderAvailability(h),100)}).observe(h,{childList:true,subtree:false})}});if(typeof window.loadAll==='function'&&!window.__partnerTeamLoadPatched){const old=window.loadAll;window.loadAll=async function(...args){const r=await old.apply(this,args);scheduleDecorate();return r};window.__partnerTeamLoadPatched=true}}
const style=document.createElement('style');style.textContent='.td-partner-member{display:flex;align-items:center;gap:12px}.td-partner-member img{width:52px;height:52px;border-radius:50%;object-fit:cover;border:2px solid rgba(134,229,74,.35);cursor:pointer}.td-partner-member div{display:grid;gap:4px}.td-own-team{display:block;margin-top:3px;font-size:10px;font-style:normal;font-weight:900;color:#86e54a;text-transform:uppercase;letter-spacing:.04em}';document.head.appendChild(style);
if(document.readyState==='loading')addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.TeamDuckPartnerTeams={refresh:scheduleDecorate};
})();
