(()=>{
const q=id=>document.getElementById(id),photoCache=new Map();
const getMe=()=>{try{return me||null}catch(_){return null}},getTeam=()=>{try{return Array.isArray(team)?team:[]}catch(_){return[]}};
const role=()=>window.TeamDuckRoleLayout?.effectiveRole?.()||getMe()?.role||null,partnerId=()=>String(getMe()?.id||''),isPartner=()=>role()==='partner',isRealPartner=()=>getMe()?.role==='partner';
const ownMember=p=>isRealPartner()&&String(p?.owner_partner_id||'')===partnerId();
async function signed(p){if(!p?.photo_path)return '/401FB0DA-DAD2-49CE-89E0-A9850A0722F7.png';if(photoCache.has(p.photo_path))return photoCache.get(p.photo_path);const r=await sb.storage.from('team-images').createSignedUrl(p.photo_path,3600);const u=r.error?'/401FB0DA-DAD2-49CE-89E0-A9850A0722F7.png':r.data.signedUrl;photoCache.set(p.photo_path,u);return u}
async function showPerson(p,e){e?.stopPropagation?.();if(!p)return;if(window.TeamDuckImages?.showPersonPhoto)return window.TeamDuckImages.showPersonPhoto(p)}
function teamNav(){return [...document.querySelectorAll('#nav button')].find(b=>b.dataset.page==='team')||null}
function prepare(){if(!isPartner())return;const nav=teamNav();nav?.classList.remove('hidden');if(nav)nav.style.removeProperty('display');const page=q('team');if(page)page.classList.toggle('hidden',!nav?.classList.contains('active'));if(isRealPartner())q('newMember')?.classList.remove('hidden');const h=page?.querySelector('h2');if(h)h.textContent='A minha equipa';if(q('inviteRole'))q('inviteRole').value='substitute';q('inviteRole')?.closest('label')?.classList.add('hidden');q('inviteForm')?.querySelector('fieldset')?.classList.add('hidden');if(isRealPartner()&&q('newMember'))q('newMember').onclick=()=>{q('inviteRole').value='substitute';q('inviteDialog')?.showModal()}}
async function renderTeam(){if(!isPartner())return;prepare();const host=q('teamList');if(!host)return;let rows=[];if(isRealPartner()){const self=getTeam().find(p=>String(p.id)===partnerId())||getMe();rows=[self,...getTeam().filter(p=>String(p.id)!==partnerId()&&ownMember(p))].filter(Boolean)}host.innerHTML='';for(const p of rows){const isSelf=String(p.id)===partnerId(),u=await signed(p),card=document.createElement('article');card.className='item'+(isSelf?' clickable td-self-profile':'');card.dataset.member=p.id;card.innerHTML=`<div class="td-partner-member"><img src="${u}" alt=""><div><strong class="td-person-name-link">${esc(p.full_name||p.email||'Membro')}</strong><small>${esc(p.base_city||'Cidade base por definir')} · ${isSelf?'A minha ficha':'Substituto'}</small></div></div>`;card.querySelector('img').onclick=e=>isSelf?null:showPerson(p,e);card.querySelector('strong').onclick=e=>{e.stopPropagation();if(isSelf){q('memberDialog')?.classList.remove('hidden');try{openMember(p.id)}catch(_){}}else showPerson(p,e)};if(isSelf)card.onclick=()=>{q('memberDialog')?.classList.remove('hidden');try{openMember(p.id)}catch(_){}};host.appendChild(card)}if(!rows.length)host.innerHTML='<div class="empty">A tua ficha ainda não está disponível.</div>';window.TeamDuckImages?.enhance?.()}
async function decorateSubstituteLists(){if(!isPartner())return;const people=getTeam();for(const row of document.querySelectorAll('.td-avail-row')){const id=row.dataset.techId,name=row.querySelector('b')?.textContent?.trim(),p=people.find(x=>String(x.id)===String(id))||people.find(x=>String(x.full_name||x.email||'').trim()===name);if(!p)continue;let img=row.querySelector('img');if(!img){img=document.createElement('img');row.prepend(img)}img.src=await signed(p);img.alt=p.full_name||'Técnico';img.style.visibility='visible';img.onclick=e=>showPerson(p,e);const n=row.querySelector('b');if(n){n.classList.add('td-person-name-link');n.onclick=e=>showPerson(p,e)}}}
async function decorateAgendaSubs(){if(!isPartner())return;const people=getTeam();for(const card of document.querySelectorAll('#concerts>.item')){const text=card.textContent||'',p=people.find(x=>text.includes(x.full_name||x.email||'__'));if(!p)continue;let img=card.querySelector('.td-compact-avatar');if(!img){img=document.createElement('img');img.className='td-compact-avatar';card.querySelector('div')?.prepend(img)}img.src=await signed(p);img.style.visibility='visible';img.onclick=e=>showPerson(p,e)}}
function refresh(){setTimeout(async()=>{prepare();await renderTeam();await decorateSubstituteLists();await decorateAgendaSubs()},120)}
function wireInvite(){const f=q('inviteForm');if(!f||f.dataset.partnerTeamWired)return;f.dataset.partnerTeamWired='1';const original=f.onsubmit;f.onsubmit=async e=>{if(!isRealPartner())return original?.call(f,e);e.preventDefault();const email=q('inviteMemberEmail')?.value.trim();if(!email)return;const r=await sb.functions.invoke('create-team-invite',{body:{email,role:'substitute',permissions:{}}});if(r.error||!r.data?.ok)return toast(r.data?.error||r.error?.message||'Erro ao criar convite');const link=`${location.origin}${location.pathname}?invite=${encodeURIComponent(r.data.invitation.token)}`;q('inviteDialog')?.close();q('inviteLink').value=link;q('inviteLinkDialog')?.showModal();f.reset();q('inviteRole').value='substitute';toast('Convite criado para a tua equipa.')}}
function boot(){wireInvite();refresh();document.addEventListener('click',e=>{if(e.target.closest('#nav button[data-page="team"],#nav button[data-agenda-filter="SUB"],#newMember,[data-dual-action]'))refresh()},{passive:true});if(typeof window.loadAll==='function'&&!window.__partnerTeamLoadPatched){const old=window.loadAll;window.loadAll=async function(...args){const r=await old.apply(this,args);refresh();return r};window.__partnerTeamLoadPatched=true}}
const style=document.createElement('style');style.textContent='.td-partner-member{display:flex;align-items:center;gap:12px}.td-partner-member img,.td-avail-row img,.td-compact-avatar{width:52px;height:52px;border-radius:50%;object-fit:cover;border:2px solid rgba(134,229,74,.35);cursor:pointer;flex:0 0 auto}.td-partner-member div{display:grid;gap:4px}.td-person-name-link{cursor:pointer!important;text-decoration:underline;text-decoration-style:dotted;text-underline-offset:4px}.td-person-name-link:hover{opacity:.85}';document.head.appendChild(style);
if(document.readyState==='loading')addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.TeamDuckPartnerTeams={refresh};
})();