(()=>{
const q=id=>document.getElementById(id),photoCache=new Map();
const getMe=()=>{try{return me||null}catch(_){return null}},getTeam=()=>{try{return Array.isArray(team)?team:[]}catch(_){return[]}};
const role=()=>window.TeamDuckRoleLayout?.effectiveRole?.()||getMe()?.role||null,partnerId=()=>String(getMe()?.id||''),isPartner=()=>role()==='partner',isRealPartner=()=>getMe()?.role==='partner';
const ownMember=p=>isRealPartner()&&String(p?.owner_partner_id||'')===partnerId();
async function signed(p){if(!p?.photo_path)return '/401FB0DA-DAD2-49CE-89E0-A9850A0722F7.png';if(photoCache.has(p.photo_path))return photoCache.get(p.photo_path);const r=await sb.storage.from('team-images').createSignedUrl(p.photo_path,3600);const u=r.error?'/401FB0DA-DAD2-49CE-89E0-A9850A0722F7.png':r.data.signedUrl;photoCache.set(p.photo_path,u);return u}
function teamNav(){return [...document.querySelectorAll('#nav button')].find(b=>b.dataset.page==='team')||null}
function prepare(){if(!isPartner())return;const nav=teamNav();nav?.classList.remove('hidden');if(nav)nav.style.removeProperty('display');const page=q('team');if(page)page.classList.toggle('hidden',!nav?.classList.contains('active'));if(isRealPartner())q('newMember')?.classList.remove('hidden');const h=page?.querySelector('h2');if(h)h.textContent='A minha equipa';if(q('inviteRole'))q('inviteRole').value='substitute';q('inviteRole')?.closest('label')?.classList.add('hidden');q('inviteForm')?.querySelector('fieldset')?.classList.add('hidden');if(isRealPartner()&&q('newMember'))q('newMember').onclick=()=>{q('inviteRole').value='substitute';q('inviteDialog')?.showModal()}}
async function renderTeam(){if(!isPartner())return;prepare();const host=q('teamList');if(!host)return;const rows=isRealPartner()?getTeam().filter(ownMember):[];host.innerHTML='';for(const p of rows){const u=await signed(p),card=document.createElement('article');card.className='item';card.innerHTML=`<div class="td-partner-member"><img src="${u}" alt=""><div><strong>${esc(p.full_name||p.email||'Substituto')}</strong><small>${esc(p.base_city||'Cidade base por definir')} · Substituto</small></div></div>`;card.querySelector('img').onclick=e=>{e.stopPropagation();window.TeamDuckImages?.showPersonPhoto?.(p)};host.appendChild(card)}if(!rows.length)host.innerHTML=`<div class="empty">${isRealPartner()?'Ainda não adicionaste substitutos à tua equipa.':'Pré-visualização de parceiro · a equipa real só aparece na conta do parceiro.'}</div>`}
function ensureDirectory(){let host=q('partnerSubDirectory');if(host)return host;const agenda=q('agenda'),concerts=q('concerts');if(!agenda||!concerts)return null;host=document.createElement('section');host.id='partnerSubDirectory';host.className='panel hidden';host.innerHTML='<div class="title-row"><div><strong>Substitutos</strong><small>Fotografia, nome e cidade base</small></div></div><div id="partnerSubDirectoryList" class="list"></div>';concerts.insertAdjacentElement('beforebegin',host);return host}
async function renderDirectory(){if(!isPartner())return;const host=ensureDirectory();if(!host)return;const active=!!document.querySelector('#nav button[data-agenda-filter="SUB"].active');host.classList.toggle('hidden',!active);if(!active)return;const list=q('partnerSubDirectoryList');const rows=getTeam().filter(p=>p.role==='substitute'&&p.active!==false).sort((a,b)=>{const oa=ownMember(a)?0:1,ob=ownMember(b)?0:1;if(oa!==ob)return oa-ob;return String(a.full_name||a.email||'').localeCompare(String(b.full_name||b.email||''),'pt')});list.innerHTML='';for(const p of rows){const u=await signed(p),card=document.createElement('article');card.className='item td-sub-directory-card';card.innerHTML=`<div class="td-partner-member"><img src="${u}" alt=""><div><strong>${esc(p.full_name||p.email||'Substituto')}</strong><small>${esc(p.base_city||'Cidade base por definir')}${ownMember(p)?' · Minha equipa':''}</small></div></div>`;card.querySelector('img').onclick=e=>{e.stopPropagation();window.TeamDuckImages?.showPersonPhoto?.(p)};list.appendChild(card)}if(!rows.length)list.innerHTML='<div class="empty">Sem substitutos registados.</div>'}
async function decorateSubstituteLists(){if(!isPartner())return;const people=getTeam();for(const row of document.querySelectorAll('.td-avail-row')){const id=row.dataset.techId,name=row.querySelector('b')?.textContent?.trim(),p=people.find(x=>String(x.id)===String(id))||people.find(x=>String(x.full_name||x.email||'').trim()===name);if(!p)continue;let img=row.querySelector('img');if(!img){img=document.createElement('img');row.prepend(img)}img.src=await signed(p);img.alt=p.full_name||'Técnico';img.style.visibility='visible';img.onclick=e=>{e.stopPropagation();window.TeamDuckImages?.showPersonPhoto?.(p)}}}
function refresh(){setTimeout(async()=>{prepare();await renderTeam();await renderDirectory();await decorateSubstituteLists()},180)}
function wireInvite(){const f=q('inviteForm');if(!f||f.dataset.partnerTeamWired)return;f.dataset.partnerTeamWired='1';const original=f.onsubmit;f.onsubmit=async e=>{if(!isRealPartner())return original?.call(f,e);e.preventDefault();const email=q('inviteMemberEmail')?.value.trim();if(!email)return;const r=await sb.functions.invoke('create-team-invite',{body:{email,role:'substitute',permissions:{}}});if(r.error||!r.data?.ok)return toast(r.data?.error||r.error?.message||'Erro ao criar convite');const link=`${location.origin}${location.pathname}?invite=${encodeURIComponent(r.data.invitation.token)}`;q('inviteDialog')?.close();q('inviteLink').value=link;q('inviteLinkDialog')?.showModal();f.reset();q('inviteRole').value='substitute';toast('Convite criado para a tua equipa.')}}
function boot(){wireInvite();refresh();document.addEventListener('click',e=>{if(e.target.closest('#nav button[data-page="team"],#nav button[data-agenda-filter="SUB"],#nav button[data-page="agenda"],#newMember,[data-dual-action]'))refresh()},{passive:true});if(typeof window.loadAll==='function'&&!window.__partnerTeamLoadPatched){const old=window.loadAll;window.loadAll=async function(...args){const r=await old.apply(this,args);refresh();return r};window.__partnerTeamLoadPatched=true}}
const style=document.createElement('style');style.textContent='.td-partner-member{display:flex;align-items:center;gap:12px}.td-partner-member img,.td-avail-row img{width:52px;height:52px;border-radius:50%;object-fit:cover;border:2px solid rgba(134,229,74,.35);cursor:pointer;flex:0 0 auto}.td-partner-member div{display:grid;gap:4px}#partnerSubDirectory{margin-bottom:12px}.td-sub-directory-card{padding:12px!important}';document.head.appendChild(style);
if(document.readyState==='loading')addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.TeamDuckPartnerTeams={refresh};
})();