(()=>{
const BUCKET='team-images',PLACEHOLDER='401FB0DA-DAD2-49CE-89E0-A9850A0722F7.png?v=20260821-avatar2';const cache=new Map();let timer=null,running=false,again=false;
async function signed(path){if(!path)return PLACEHOLDER;if(cache.has(path))return cache.get(path);const r=await sb.storage.from(BUCKET).createSignedUrl(path,3600),u=r.error?PLACEHOLDER:r.data.signedUrl;cache.set(path,u);return u}
async function upload(kind,id,file){if(!file||!id)return;if(!/^image\//.test(file.type)&&!/(heic|heif)$/i.test(file.name))return toast('Escolhe uma fotografia.');if(file.size>8*1024*1024)return toast('A fotografia pode ter no máximo 8 MB.');const ext=(file.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'').toLowerCase(),path=`${kind}/${id}/${Date.now()}.${ext}`,up=await sb.storage.from(BUCKET).upload(path,file,{contentType:file.type||'image/jpeg',upsert:false});if(up.error)return toast('Falha ao carregar fotografia: '+up.error.message);const list=kind==='artists'?artists:team,table=kind==='artists'?'artists':'profiles',old=list.find(x=>x.id===id)?.photo_path,save=await sb.from(table).update({photo_path:path}).eq('id',id);if(save.error){await sb.storage.from(BUCKET).remove([path]);return toast(save.error.message)}if(old)await sb.storage.from(BUCKET).remove([old]);cache.delete(old);toast('Fotografia atualizada');await loadAll()}
function picker(kind,id){const i=document.createElement('input');i.type='file';i.accept='image/*,.heic,.heif';i.hidden=true;i.onchange=()=>upload(kind,id,i.files?.[0]);document.body.appendChild(i);i.click();setTimeout(()=>i.remove(),60000)}
function ensurePhotoDialog(){if(document.getElementById('tdPersonPhotoDialog'))return;document.body.insertAdjacentHTML('beforeend',`<dialog id="tdPersonPhotoDialog" class="td-person-photo-dialog"><div class="td-person-photo-shell"><div class="title-row"><div><strong id="tdPersonPhotoName">Identificação</strong><small id="tdPersonPhotoKind">Fotografia de identificação</small></div><button type="button" class="secondary tiny" data-photo-close>Fechar</button></div><img id="tdPersonPhotoLarge" alt="Fotografia"></div></dialog>`);const d=document.getElementById('tdPersonPhotoDialog');d.querySelector('[data-photo-close]').onclick=()=>d.close();d.addEventListener('click',e=>{if(e.target===d)d.close()})}
async function showIdentityPhoto(item,kind='person'){if(!item)return;ensurePhotoDialog();const u=await signed(item.photo_path);document.getElementById('tdPersonPhotoName').textContent=kind==='artist'?(item.name||'Artista'):(item.full_name||item.email||'Técnico');document.getElementById('tdPersonPhotoKind').textContent=kind==='artist'?'Fotografia do artista':'Fotografia de identificação';const img=document.getElementById('tdPersonPhotoLarge');img.src=u;img.onerror=()=>img.src=PLACEHOLDER;if(!document.getElementById('tdPersonPhotoDialog').open)document.getElementById('tdPersonPhotoDialog').showModal()}
async function showPersonPhoto(personOrId){const p=typeof personOrId==='object'?personOrId:(team||[]).find(x=>String(x.id)===String(personOrId));return showIdentityPhoto(p,'person')}
async function showArtistPhoto(artistOrId){const a=typeof artistOrId==='object'?artistOrId:(artists||[]).find(x=>String(x.id)===String(artistOrId));return showIdentityPhoto(a,'artist')}
function avatar(url,cls,item=null,kind='person'){const img=document.createElement('img');img.className=cls;img.src=url;img.alt='';img.loading='lazy';img.decoding='async';img.onerror=()=>img.src=PLACEHOLDER;if(item){img.classList.add('td-photo-clickable');img.onclick=e=>{e.stopPropagation();kind==='artist'?showArtistPhoto(item):showPersonPhoto(item)}}return img}
async function enhanceArtists(){for(const a of artists||[]){const card=document.querySelector(`[data-artist-files="${a.id}"]`)?.closest('.item');if(!card||card.dataset.photoDone)continue;card.dataset.photoDone='1';const u=await signed(a.photo_path),left=card.firstElementChild;if(left){left.classList.add('td-identity');left.prepend(avatar(u,'td-artist-photo',a,'artist'));const n=left.querySelector('strong');if(n){n.classList.add('td-name-photo-link');n.onclick=e=>{e.stopPropagation();showArtistPhoto(a)}}}if(can('artists_manage')){const b=document.createElement('button');b.type='button';b.className='secondary tiny';b.textContent=a.photo_path?'Trocar foto':'Adicionar foto';b.onclick=e=>{e.stopPropagation();picker('artists',a.id)};card.lastElementChild?.prepend(b)}}}
async function enhanceTeam(){for(const p of team||[]){const card=document.querySelector(`[data-member="${p.id}"]`);if(!card||card.dataset.photoDone)continue;card.dataset.photoDone='1';const u=await signed(p.photo_path),left=card.firstElementChild;if(left){left.classList.add('td-identity');left.prepend(avatar(u,'td-member-photo',p));const n=left.querySelector('strong');if(n){n.classList.add('td-name-photo-link');n.onclick=e=>{e.stopPropagation();showPersonPhoto(p)}}}if(me?.role==='admin'){const b=document.createElement('button');b.type='button';b.className='secondary tiny td-photo-btn';b.textContent=p.photo_path?'Trocar foto':'Adicionar foto';b.onclick=e=>{e.stopPropagation();picker('profiles',p.id)};card.appendChild(b)}}}
async function enhance(){if(running){again=true;return}running=true;try{await Promise.all([enhanceArtists(),enhanceTeam()])}finally{running=false;if(again){again=false;schedule(100)}}}
function schedule(ms=100){clearTimeout(timer);timer=setTimeout(enhance,ms)}
function boot(){ensurePhotoDialog();schedule(160);if(typeof window.loadAll==='function'&&!window.__profileImagesPatched){const old=window.loadAll;window.loadAll=async function(...args){const r=await old.apply(this,args);schedule(120);return r};window.__profileImagesPatched=true}const css=document.createElement('style');css.textContent='.td-identity{display:grid!important;grid-template-columns:auto 1fr;column-gap:10px;align-items:center}.td-identity>strong,.td-identity>small{grid-column:2}.td-artist-photo,.td-member-photo{grid-column:1;grid-row:1/3;width:48px;height:48px;border-radius:14px;object-fit:cover;background:#0b2b19;border:1px solid rgba(255,255,255,.15);cursor:pointer}.td-member-photo{border-radius:50%}.td-photo-btn{margin-left:auto}.td-photo-clickable,.td-name-photo-link{cursor:pointer!important}.td-person-photo-dialog{width:min(calc(100% - 24px),520px)!important;padding:0!important;background:#050807!important}.td-person-photo-shell{padding:18px}.td-person-photo-shell .title-row small{display:block;color:#aab0ac;margin-top:3px}.td-person-photo-shell>img{display:block;width:100%;max-height:70vh;object-fit:contain;border-radius:22px;margin-top:16px;background:#08120c;border:1px solid rgba(255,255,255,.12)}@media(max-width:600px){.td-artist-photo,.td-member-photo{width:44px;height:44px}.td-person-photo-shell{padding:14px}}';document.head.appendChild(css)}
if(document.readyState==='loading')addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.TeamDuckImages={enhance:()=>schedule(0),picker,signed,showPersonPhoto,showArtistPhoto};
})();
