(()=>{
const BUCKET='team-images',PLACEHOLDER='401FB0DA-DAD2-49CE-89E0-A9850A0722F7.png?v=20260820-avatar1';
const cache=new Map();
async function signed(path){if(!path)return PLACEHOLDER;if(cache.has(path))return cache.get(path);const r=await sb.storage.from(BUCKET).createSignedUrl(path,3600);const u=r.error?PLACEHOLDER:r.data.signedUrl;cache.set(path,u);return u}
async function upload(kind,id,file){if(!file||!id)return;if(!/^image\//.test(file.type)&&!/(heic|heif)$/i.test(file.name))return toast('Escolhe uma fotografia.');if(file.size>8*1024*1024)return toast('A fotografia pode ter no máximo 8 MB.');const ext=(file.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'').toLowerCase(),path=`${kind}/${id}/${Date.now()}.${ext}`;const up=await sb.storage.from(BUCKET).upload(path,file,{contentType:file.type||'image/jpeg',upsert:false});if(up.error)return toast('Falha ao carregar fotografia: '+up.error.message);const table=kind==='artists'?'artists':'profiles',old=(kind==='artists'?artists:team).find(x=>x.id===id)?.photo_path;const save=await sb.from(table).update({photo_path:path}).eq('id',id);if(save.error){await sb.storage.from(BUCKET).remove([path]);return toast(save.error.message)}if(old)await sb.storage.from(BUCKET).remove([old]);cache.delete(old);toast('Fotografia atualizada');await loadAll();setTimeout(enhance,50)}
function picker(kind,id){const i=document.createElement('input');i.type='file';i.accept='image/*,.heic,.heif';i.style.display='none';i.onchange=()=>upload(kind,id,i.files?.[0]);document.body.appendChild(i);i.click();setTimeout(()=>i.remove(),60000)}
function avatar(url,cls='td-avatar'){const img=document.createElement('img');img.className=cls;img.src=url;img.alt='';img.onerror=()=>img.src=PLACEHOLDER;return img}
async function enhanceArtists(){for(const a of artists||[]){const card=document.querySelector(`[data-artist-files="${a.id}"]`)?.closest('.item');if(!card||card.dataset.photoDone)return;card.dataset.photoDone='1';const u=await signed(a.photo_path);const left=card.firstElementChild;if(left){left.classList.add('td-identity');left.prepend(avatar(u,'td-artist-photo'))}if(can('artists_manage')){const b=document.createElement('button');b.type='button';b.className='secondary tiny';b.textContent=a.photo_path?'Trocar foto':'Adicionar foto';b.onclick=e=>{e.stopPropagation();picker('artists',a.id)};card.lastElementChild?.prepend(b)}}}
async function enhanceTeam(){for(const p of team||[]){const card=document.querySelector(`[data-member="${p.id}"]`);if(!card||card.dataset.photoDone)return;card.dataset.photoDone='1';const u=await signed(p.photo_path);const left=card.firstElementChild;if(left){left.classList.add('td-identity');left.prepend(avatar(u,'td-member-photo'))}if(me?.role==='admin'){const b=document.createElement('button');b.type='button';b.className='secondary tiny td-photo-btn';b.textContent=p.photo_path?'Trocar foto':'Adicionar foto';b.onclick=e=>{e.stopPropagation();picker('profiles',p.id)};card.appendChild(b)}}}
async function enhanceConcerts(){const map=new Map((artists||[]).map(a=>[a.name,a]));for(const card of document.querySelectorAll('#concerts .item,#closedConcerts .item,#nextWeekConcerts .item,#nextMonthConcerts .item,#nextConcerts .item')){if(card.dataset.artistPhotoDone)continue;const strong=card.querySelector('strong');const a=map.get(strong?.textContent?.trim());if(!a)continue;card.dataset.artistPhotoDone='1';const u=await signed(a.photo_path);const left=strong.closest('div');if(left){left.classList.add('td-identity');left.prepend(avatar(u,'td-artist-photo'))}}}
async function enhance(){await Promise.all([enhanceArtists(),enhanceTeam(),enhanceConcerts()])}
const css=document.createElement('style');css.textContent='.td-identity{display:grid!important;grid-template-columns:auto 1fr;column-gap:10px;align-items:center}.td-identity>strong,.td-identity>small{grid-column:2}.td-artist-photo,.td-member-photo{grid-column:1;grid-row:1/3;width:48px;height:48px;border-radius:14px;object-fit:cover;background:#0b2b19;border:1px solid rgba(255,255,255,.15)}.td-member-photo{border-radius:50%}.td-photo-btn{margin-left:auto}@media(max-width:600px){.td-artist-photo,.td-member-photo{width:44px;height:44px}}';document.head.appendChild(css);
if(typeof window.loadAll==='function'&&!window.__profileImagesPatched){const old=window.loadAll;window.loadAll=async function(...args){const r=await old.apply(this,args);setTimeout(enhance,20);setTimeout(enhance,350);return r};window.__profileImagesPatched=true}
new MutationObserver(()=>setTimeout(enhance,20)).observe(document.body,{childList:true,subtree:true});addEventListener('load',()=>setTimeout(enhance,500));window.TeamDuckImages={enhance,picker};
})();