(()=>{
const q=id=>document.getElementById(id),hide=el=>el&&el.classList.add('hidden'),show=el=>el&&el.classList.remove('hidden');
const PREVIEW_KEY='team-duck-role-preview',DEMO_KEY='team-duck-demo-mode';
function actualRole(){try{return me?.role||null}catch(_){return null}}function demoActive(){return sessionStorage.getItem(DEMO_KEY)==='1'}
function currentUserId(){try{return String(me?.id||'')}catch(_){return ''}}function previewRole(){if(actualRole()!=='admin')return null;const v=sessionStorage.getItem(PREVIEW_KEY);return ['partner','substitute'].includes(v)?v:null}function effectiveRole(){return previewRole()||actualRole()}function isPreview(){return actualRole()==='admin'&&!!previewRole()}
function navButton(page,filter){return [...document.querySelectorAll('#nav button')].find(b=>b.dataset.page===page&&(filter?b.dataset.agendaFilter===filter:!b.dataset.agendaFilter))}
function hideAdminOnly(opts={}){if(!opts.keepTeam){hide(q('team'));hide(navButton('team'));hide(q('newMember'));hide(q('inviteDialog'));hide(q('inviteLinkDialog'))}hide(q('memberDialog'));document.querySelectorAll('[data-team-action],[data-admin-only]').forEach(hide)}
function addPreviewControl(){const wrap=q('rolePreviewControl');if(!wrap)return;if(demoActive()){show(wrap);return}if(actualRole()!=='admin'){show(wrap);return}show(wrap);const sel=q('rolePreviewSelect');if(!sel)return;/* demo-mode owns this selector; role-layout must never replace its onchange/options */if(window.TeamDuckDemo)return;sel.value=previewRole()||'admin';q('rolePreviewNotice')?.remove();if(isPreview()){const tag=document.createElement('div');tag.id='rolePreviewNotice';tag.textContent=`Pré-visualização: ${previewRole()==='partner'?'Parceiro':'Substituto'} · dados pessoais reais estão protegidos`;tag.style.cssText='position:sticky;top:0;z-index:50;background:#183321;color:#dff8df;border-bottom:1px solid #3f7b4e;padding:7px 12px;text-align:center;font-size:12px;font-weight:800';q('app')?.prepend(tag)}}
function emptyHost(id,text){const el=q(id);if(el)el.innerHTML=`<div class="empty">${text}</div>`}
function applyAdmin(){show(navButton('dashboard'));show(navButton('agenda'));show(navButton('agenda','FOH'));show(navButton('agenda','ROH'));show(navButton('agenda','SUB'));show(navButton('closed'));show(navButton('artists'));show(navButton('team'));show(q('newConcert'));show(q('newArtist'));show(q('newMember'));document.querySelectorAll('#concerts > .item').forEach(card=>{card.dataset.memberHidden='0';card.dataset.filterHidden='0';card.style.display=''});q('agendaFilterEmpty')?.classList.add('hidden');window.TeamDuckFinance?.refresh?.();window.TeamDuckDashboardWindows?.refresh?.()}
function applySafePartnerPreview(){if(!isPreview()||previewRole()!=='partner')return false;['concerts','closedConcerts','artistList','nextWeekConcerts','nextMonthConcerts','nextConcerts'].forEach(id=>emptyHost(id,id==='artistList'?'Sem artistas criados por este Parceiro.':'Sem dados deste Parceiro.'));return true}
function filterCardsForPartner(){if(isPreview()){applySafePartnerPreview();return}const id=currentUserId();[...document.querySelectorAll('#concerts > .item')].forEach((card,i)=>{const c=(concerts||[])[i];card.style.display=c&&String(c.principal_technician_id||c.owner_id||'')===id?'':'none'})}
function applyPartner(){hideAdminOnly({keepTeam:true});['dashboard','agenda','closed','artists','team'].forEach(p=>show(navButton(p)));['FOH','ROH','SUB'].forEach(f=>show(navButton('agenda',f)));show(q('team'));show(q('newConcert'));show(q('newArtist'));if(actualRole()==='partner')show(q('newMember'));filterCardsForPartner();window.TeamDuckPartnerTeams?.refresh?.();window.TeamDuckScopedTeam?.refresh?.()}
function filterCardsForSubstitute(){const host=q('concerts');if(!host)return;if(isPreview()){emptyHost('concerts','Sem datas atribuídas a este Substituto.');return}const id=currentUserId();[...host.querySelectorAll(':scope > .item')].forEach((card,i)=>{const c=(concerts||[])[i];card.style.display=c&&String(c.substitute_technician_id||'')===id?'':'none'})}
function applySubstitute(){hideAdminOnly({keepTeam:true});hide(navButton('dashboard'));hide(navButton('closed'));['FOH','ROH','SUB'].forEach(f=>hide(navButton('agenda',f)));show(navButton('agenda'));show(navButton('artists'));show(navButton('team'));show(q('team'));hide(q('newConcert'));hide(q('newArtist'));hide(q('newMember'));filterCardsForSubstitute();window.TeamDuckScopedTeam?.refresh?.()}
function applyRoleLayout(){addPreviewControl();if(demoActive())return true;const role=effectiveRole();if(!role)return false;document.body.dataset.teamDuckRole=role;document.body.dataset.actualRole=actualRole()||'';if(role==='admin')applyAdmin();else if(role==='partner')applyPartner();else if(role==='substitute')applySubstitute();return true}
function patchLoadAll(){if(window.__roleLayoutPatched||typeof loadAll!=='function')return;const original=loadAll;window.loadAll=async function(...args){const out=await original.apply(this,args);setTimeout(applyRoleLayout,0);setTimeout(applyRoleLayout,220);return out};window.__roleLayoutPatched=true}
function init(){patchLoadAll();let n=0;const tick=()=>{n++;patchLoadAll();const done=applyRoleLayout();if(!done&&n<40)setTimeout(tick,200)};tick()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();window.TeamDuckRoleLayout={apply:applyRoleLayout,effectiveRole,clearPreview:()=>{sessionStorage.removeItem(PREVIEW_KEY);location.reload()}};
})();