(()=>{
const q=id=>document.getElementById(id);const getTeam=()=>{try{return Array.isArray(team)?team:[]}catch(_){return[]}},uid=()=>String(me?.id||''),actualRole=()=>me?.role||'',effectiveRole=()=>window.TeamDuckRoleLayout?.effectiveRole?.()||actualRole();
function visiblePeople(){return getTeam().filter(p=>p?.active!==false)}
function openSelf(){document.getElementById('memberDialog')?.classList.remove('hidden');try{openMember(uid())}catch(_){}}
function render(){const mode=effectiveRole();if(!['partner','substitute'].includes(mode))return;const host=q('teamList');if(!host)return;const people=visiblePeople();host.innerHTML=people.map(p=>`<article class="item ${String(p.id)===uid()?'clickable td-self-profile':''}" data-member="${p.id}"><div><strong>${esc(p.full_name||p.email||'Membro')}</strong><small>${esc(p.base_city||'Cidade base por definir')} · ${String(p.id)===uid()?'A minha ficha':roleLabel(p.role)}</small></div></article>`).join('')||'<div class="empty">Ainda não existem membros ativos.</div>';host.querySelectorAll('[data-member]').forEach(card=>{const id=card.dataset.member;if(id===uid())card.onclick=openSelf;else card.onclick=()=>window.TeamDuckImages?.showPersonPhoto?.(id)});window.TeamDuckImages?.enhance?.();setTimeout(()=>window.TeamDuckImages?.enhance?.(),120)}
function patchOpen(){if(window.__scopedTeamOpenPatched)return;const old=window.openMember;if(typeof old!=='function')return;window.openMember=function(id){const mode=effectiveRole();if(['partner','substitute'].includes(mode)&&String(id)!==uid())return window.TeamDuckImages?.showPersonPhoto?.(id);q('memberDialog')?.classList.remove('hidden');return old(id)};window.__scopedTeamOpenPatched=true}
function refresh(){patchOpen();render()}
function boot(){refresh();if(typeof window.loadAll==='function'&&!window.__scopedTeamLoadPatched){const old=window.loadAll;window.loadAll=async function(...args){const r=await old.apply(this,args);setTimeout(refresh,160);return r};window.__scopedTeamLoadPatched=true}}
if(document.readyState==='loading')addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.TeamDuckScopedTeam={refresh};
})();