(()=>{
const q=id=>document.getElementById(id);const getTeam=()=>{try{return Array.isArray(team)?team:[]}catch(_){return[]}},uid=()=>String(me?.id||''),role=()=>me?.role||'';
function relatedIds(){const ids=new Set([uid()]);for(const c of concerts||[]){const members=[c.principal_technician_id,c.technician_id,c.owner_id,c.substitute_technician_id].filter(Boolean).map(String);if(members.includes(uid()))members.forEach(x=>ids.add(x))}if(role()==='partner')getTeam().filter(p=>String(p.owner_partner_id||'')===uid()).forEach(p=>ids.add(String(p.id)));const self=getTeam().find(p=>String(p.id)===uid());if(role()==='substitute'&&self?.owner_partner_id)ids.add(String(self.owner_partner_id));return ids}
function visiblePeople(){const ids=relatedIds(),rows=getTeam().filter(p=>ids.has(String(p.id)));if(!rows.some(p=>String(p.id)===uid())&&me)rows.unshift(me);return rows}
function openSelf(){q('memberDialog')?.classList.remove('hidden');try{openMember(uid())}catch(_){}}
function render(){if(!['partner','substitute'].includes(role()))return;const host=q('teamList');if(!host)return;const people=visiblePeople();host.innerHTML=people.map(p=>`<article class="item ${String(p.id)===uid()?'clickable td-self-profile':''}" data-member="${p.id}"><div><strong>${esc(p.full_name||p.email||'Membro')}</strong><small>${esc(p.base_city||'Cidade base por definir')} · ${roleLabel(p.role)}${String(p.id)===uid()?' · A minha ficha':''}</small></div></article>`).join('')||'<div class="empty">A tua ficha ainda não está disponível.</div>';host.querySelectorAll('[data-member]').forEach(card=>{const id=card.dataset.member;if(id===uid())card.onclick=openSelf;else card.onclick=()=>window.TeamDuckImages?.showPersonPhoto?.(id)});window.TeamDuckImages?.enhance?.();setTimeout(()=>window.TeamDuckImages?.enhance?.(),120)}
function patchOpen(){if(window.__scopedTeamOpenPatched)return;const old=window.openMember;if(typeof old!=='function')return;window.openMember=function(id){if(['partner','substitute'].includes(role())&&String(id)!==uid())return window.TeamDuckImages?.showPersonPhoto?.(id);q('memberDialog')?.classList.remove('hidden');return old(id)};window.__scopedTeamOpenPatched=true}
function refresh(){patchOpen();render()}
function boot(){refresh();if(typeof window.loadAll==='function'&&!window.__scopedTeamLoadPatched){const old=window.loadAll;window.loadAll=async function(...args){const r=await old.apply(this,args);setTimeout(refresh,160);return r};window.__scopedTeamLoadPatched=true}}
if(document.readyState==='loading')addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.TeamDuckScopedTeam={refresh};
})();