(()=>{
const MARK='tdSubSearchDone';
function isSubstituteSelect(sel){if(!(sel instanceof HTMLSelectElement))return false;const key=`${sel.id||''} ${sel.name||''} ${sel.getAttribute('aria-label')||''}`.toLowerCase();const label=sel.closest('label')?.textContent?.toLowerCase()||'';return key.includes('substitut')||label.includes('substitut')}
function openSearch(sel){document.getElementById('tdSubstituteSearchDialog')?.remove();const d=document.createElement('dialog');d.id='tdSubstituteSearchDialog';d.innerHTML=`<div class="td-sub-search-shell"><div class="title-row"><div><strong>Pesquisar substituto</strong><small>Escreve o nome para filtrar.</small></div><button type="button" class="secondary tiny" data-close>Fechar</button></div><input id="tdSubstituteSearchInput" type="search" placeholder="Pesquisar por nome…" autocomplete="off"><div id="tdSubstituteSearchResults" class="td-sub-search-results"></div></div>`;document.body.appendChild(d);const input=d.querySelector('#tdSubstituteSearchInput'),host=d.querySelector('#tdSubstituteSearchResults');const options=[...sel.options].filter(o=>o.value);const render=()=>{const term=(input.value||'').trim().toLocaleLowerCase('pt-PT');const matches=options.filter(o=>(o.textContent||'').toLocaleLowerCase('pt-PT').includes(term));host.innerHTML='';for(const o of matches){const b=document.createElement('button');b.type='button';b.className='td-sub-search-result';b.textContent=o.textContent||'Substituto';if(String(o.value)===String(sel.value))b.classList.add('active');b.onclick=()=>{sel.value=o.value;sel.dispatchEvent(new Event('change',{bubbles:true}));d.close()};host.appendChild(b)}if(!matches.length)host.innerHTML='<div class="muted" style="padding:12px">Nenhum substituto encontrado.</div>'};input.addEventListener('input',render);d.querySelector('[data-close]').onclick=()=>d.close();d.addEventListener('click',e=>{if(e.target===d)d.close()});d.addEventListener('close',()=>d.remove(),{once:true});render();d.showModal();setTimeout(()=>input.focus(),50)}
function enhance(sel){if(sel.dataset[MARK]==='1'||!isSubstituteSelect(sel))return;sel.dataset[MARK]='1';const wrap=document.createElement('span');wrap.className='td-sub-search-wrap';sel.parentNode.insertBefore(wrap,sel);wrap.appendChild(sel);const b=document.createElement('button');b.type='button';b.className='td-sub-search-btn';b.setAttribute('aria-label','Pesquisar substituto');b.title='Pesquisar substituto';b.textContent='🔎';b.onclick=e=>{e.preventDefault();e.stopPropagation();openSearch(sel)};wrap.appendChild(b)}
function scan(){document.querySelectorAll('select').forEach(enhance)}
function boot(){const style=document.createElement('style');style.textContent='.td-sub-search-wrap{display:grid;grid-template-columns:minmax(0,1fr) 42px;gap:7px;align-items:center;width:100%}.td-sub-search-wrap>select{min-width:0;width:100%}.td-sub-search-btn{height:42px;min-width:42px;padding:0;border-radius:14px;background:#0b1710;border:1px solid rgba(121,255,146,.25);color:#fff;font-size:17px}.td-sub-search-shell{padding:16px;min-width:min(92vw,430px)}.td-sub-search-shell>input{width:100%;margin:14px 0 10px}.td-sub-search-results{display:grid;gap:7px;max-height:55vh;overflow:auto}.td-sub-search-result{text-align:left;background:#0b1710;border:1px solid rgba(255,255,255,.10);border-radius:14px;padding:11px 12px;color:#fff}.td-sub-search-result.active{border-color:#69e781;box-shadow:0 0 0 1px rgba(105,231,129,.2)}';document.head.appendChild(style);scan();const mo=new MutationObserver(()=>scan());mo.observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.TeamDuckSubstituteSearch={scan};
})();
