(()=>{
const q=id=>document.getElementById(id);let busy=false,timer=null;
const rows=()=>{try{return Array.isArray(concerts)?concerts:[]}catch(_){return[]}};
const byId=id=>rows().find(c=>String(c.id)===String(id));
const isPast=c=>{const d=new Date(c?.ends_at||c?.starts_at||0);return !Number.isNaN(d.getTime())&&d.getTime()<Date.now()};
const hasSub=c=>!!c?.substitute_technician_id;
const canManage=c=>{try{if(me?.role==='admin')return true;if(me?.role!=='partner')return false;const uid=String(me?.id||'');return [c?.owner_id,c?.principal_technician_id,c?.technician_id].filter(Boolean).map(String).includes(uid)}catch(_){return false}};
async function patch(id,data,msg){if(busy)return;busy=true;try{const r=await sb.from('concerts').update(data).eq('id',id);if(r.error)return toast(r.error.message);toast(msg);await loadAll()}finally{busy=false}}
async function toggleBandInvoice(c){const next=!c.receipt_issued;await patch(c.id,{receipt_issued:next,receipt_issued_at:next?new Date().toISOString():null},next?'Fatura à banda marcada':'Faturação à banda removida')}
async function toggleBandPaid(c){const paid=!!c.payment_received_at;if(paid){await patch(c.id,{amount_received:0,payment_received_at:null,closed:false,progress_percent:hasSub(c)?75:50},'Pagamento da banda removido');return}const data={amount_received:Number(c.fee_override||0),payment_received_at:new Date().toISOString(),progress_percent:hasSub(c)?75:100};if(!hasSub(c))data.closed=true;await patch(c.id,data,hasSub(c)?'Pagamento da banda recebido · falta liquidar substituto':'Pago · trabalho concluído')}
async function toggleSubInvoice(c){const next=!c.substitute_invoice_received;await patch(c.id,{substitute_invoice_received:next,substitute_invoice_received_at:next?new Date().toISOString():null,closed:false},next?'Fatura do substituto recebida':'Fatura do substituto removida')}
async function toggleSubPaid(c){if(!c.substitute_invoice_received&&!c.substitute_paid)return toast('Marca primeiro a fatura do substituto como recebida.');const next=!c.substitute_paid;if(!next){await patch(c.id,{substitute_paid:false,substitute_paid_at:null,closed:false,progress_percent:c.payment_received_at?75:50},'Pagamento ao substituto removido');return}if(!c.payment_received_at)return toast('A data só pode fechar depois de receberes também o pagamento da banda.');await patch(c.id,{substitute_paid:true,substitute_paid_at:new Date().toISOString(),closed:true,progress_percent:100},'Substituto pago · trabalho concluído e fechado')}
function mk(label,on,handler,kind){const b=document.createElement('button');b.type='button';b.className='secondary tiny td-billing-btn'+(on?' td-billing-done':'');b.textContent=(on?'✓ ':'')+label;b.dataset.billingKind=kind;b.onclick=e=>{e.stopPropagation();handler()};return b}
function decorateCard(card,c){if(!card||!c||!isPast(c)||!canManage(c)||c.closed)return;let actions=card.querySelector('.concert-actions');if(!actions){actions=document.createElement('div');actions.className='concert-actions';card.appendChild(actions)}actions.querySelectorAll('[data-invoice],[data-paid],[data-billing-kind]').forEach(x=>x.remove());const band=document.createElement('div');band.className='td-billing-group';band.innerHTML='<small>Banda</small>';band.append(mk('Faturado',!!c.receipt_issued,()=>toggleBandInvoice(c),'band-invoice'));band.append(mk('Pago',!!c.payment_received_at,()=>toggleBandPaid(c),'band-paid'));actions.appendChild(band);if(hasSub(c)){const sub=document.createElement('div');sub.className='td-billing-group';sub.innerHTML='<small>Substituto</small>';sub.append(mk('Fatura recebida',!!c.substitute_invoice_received,()=>toggleSubInvoice(c),'sub-invoice'));sub.append(mk('Pago',!!c.substitute_paid,()=>toggleSubPaid(c),'sub-paid'));actions.appendChild(sub)}}
function refresh(){clearTimeout(timer);timer=setTimeout(()=>{const cards=[...document.querySelectorAll('#concerts>.item')];cards.forEach((card,i)=>{const id=card.dataset.concertId||card.querySelector('[data-concert-view]')?.dataset.concertView;const c=id?byId(id):rows()[i];decorateCard(card,c)});const d=q('tdCompactDetail');if(d?.open){const id=document.querySelector('#concerts>.item[aria-current="true"]')?.dataset.concertId;void id}window.TeamDuckCompactAgenda?.refresh?.()},60)}
function style(){if(q('tdBillingStyle'))return;const s=document.createElement('style');s.id='tdBillingStyle';s.textContent='.td-billing-group{display:flex;align-items:center;gap:6px;flex-wrap:wrap;padding:6px 8px;border:1px solid rgba(255,255,255,.10);border-radius:12px;background:rgba(255,255,255,.025)}.td-billing-group>small{font-size:10px;font-weight:900;letter-spacing:.08em;text-transform:uppercase;opacity:.65;margin-right:2px}.td-billing-btn.td-billing-done{background:#6f7472!important;border-color:#8a8f8d!important;color:#e6e8e7!important;filter:saturate(.1)}';document.head.appendChild(s)}
function boot(){style();refresh();if(typeof window.loadAll==='function'&&!window.__subBillingLoadPatched){const old=window.loadAll;window.loadAll=async function(...args){const r=await old.apply(this,args);refresh();return r};window.__subBillingLoadPatched=true}document.querySelectorAll('#nav button[data-page="agenda"]').forEach(b=>b.addEventListener('click',refresh))}
if(document.readyState==='loading')addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.TeamDuckSubstituteBilling={refresh};
})();