(()=>{
const q=id=>document.getElementById(id);let busy=false,timer=null;
const rows=()=>{try{return Array.isArray(concerts)?concerts:[]}catch(_){return[]}};
const byId=id=>rows().find(c=>String(c.id)===String(id));
const isPast=c=>{const d=new Date(c?.ends_at||c?.starts_at||0);return !Number.isNaN(d.getTime())&&d.getTime()<Date.now()};
const hasSub=c=>!!c?.substitute_technician_id;
const canManage=c=>{try{if(me?.role==='admin')return true;if(me?.role!=='partner')return false;const uid=String(me?.id||'');return [c?.owner_id,c?.principal_technician_id,c?.technician_id].filter(Boolean).map(String).includes(uid)}catch(_){return false}};
async function patch(id,data,msg){if(busy)return;busy=true;try{const r=await sb.from('concerts').update(data).eq('id',id);if(r.error)return toast(r.error.message);toast(msg);await loadAll()}finally{busy=false}}
async function toggleBandInvoice(c){const next=!c.receipt_issued;await patch(c.id,{receipt_issued:next,receipt_issued_at:next?new Date().toISOString():null},next?'Fatura à banda marcada':'Faturação à banda removida')}
async function toggleBandPaid(c){const paid=!!c.payment_received_at;if(paid){await patch(c.id,{amount_received:0,payment_received_at:null,closed:false,progress_percent:hasSub(c)?75:50},'Pagamento da banda removido');return}const data={amount_received:Number(c.fee_override||0),payment_received_at:new Date().toISOString(),progress_percent:hasSub(c)?75:100};if(!hasSub(c))data.closed=true;await patch(c.id,data,hasSub(c)?'Pagamento da banda recebido · falta liquidar substituto':'Pago · trabalho concluído')}
async function toggleSubInvoice(c){const next=!c.substitute_invoice_received;await patch(c.id,{substitute_invoice_received:next,substitute_invoice_received_at:next?new Date().toISOString():null,closed:false},next?'Fatura do substituto recebida':'Fatura do substituto removida')}
async function toggleSubPaid(c){if(!c.substitute_invoice_received&&!c.substitute_paid)return toast('Marca primeiro a fatura do substituto como recebida.');const next=!c.substitute_paid;if(!next){await patch(c.id,{substitute_paid:false,substitute_paid_at:null,closed:false,progress_percent:c.payment_received_at?75:50},'Pagamento ao substituto removido');return}if(!c.payment_received_at)return toast('A data só pode fechar depois de receberes também o pagamento da banda.');await patch(c.id,{substitute_paid:true,substitute_paid_at:new Date().toISOString(),closed:true,progress_percent:100},'Substituto pago · trabalho concluído e fechado')}
function mk(label,on,handler,kind){const b=document.createElement('button');b.type='button';b.className='secondary tiny td-billing-btn'+(on?' td-billing-done':'');b.textContent=(on?'✓ ':'')+label;b.dataset.billingKind=kind;b.onclick=e=>{e.stopPropagation();handler()};return b}
function compactBtn(label,on,handler,kind,title){const b=document.createElement('button');b.type='button';b.className='td-agenda-billing-chip'+(on?' td-done':'');b.textContent=(on?'✓ ':'')+label;b.dataset.billingCompact=kind;b.title=title||label;b.onclick=e=>{e.preventDefault();e.stopPropagation();handler()};return b}
function decorateSummary(card,c){const summary=card?.querySelector(':scope > .td-compact-summary');if(!summary)return;summary.querySelector('.td-agenda-billing')?.remove();if(!isPast(c)||!canManage(c)||c.closed)return;const wrap=document.createElement('div');wrap.className='td-agenda-billing';const band=document.createElement('div');band.className='td-agenda-billing-row';band.innerHTML='<small>Banda</small>';band.append(compactBtn('Faturado',!!c.receipt_issued,()=>toggleBandInvoice(c),'band-invoice','Faturação à banda'));band.append(compactBtn('Pago',!!c.payment_received_at,()=>toggleBandPaid(c),'band-paid','Pagamento recebido da banda'));wrap.appendChild(band);if(hasSub(c)){const sub=document.createElement('div');sub.className='td-agenda-billing-row';sub.innerHTML='<small>Sub</small>';sub.append(compactBtn('Fatura',!!c.substitute_invoice_received,()=>toggleSubInvoice(c),'sub-invoice','Fatura do substituto recebida'));sub.append(compactBtn('Pago',!!c.substitute_paid,()=>toggleSubPaid(c),'sub-paid','Substituto pago'));wrap.appendChild(sub)}summary.appendChild(wrap)}
function decorateCard(card,c){if(!card||!c)return;decorateSummary(card,c);if(!isPast(c)||!canManage(c)||c.closed)return;let actions=card.querySelector('.concert-actions');if(!actions){actions=document.createElement('div');actions.className='concert-actions';card.appendChild(actions)}actions.querySelectorAll('[data-invoice],[data-paid],[data-billing-kind]').forEach(x=>x.remove());const band=document.createElement('div');band.className='td-billing-group';band.innerHTML='<small>Banda</small>';band.append(mk('Faturado',!!c.receipt_issued,()=>toggleBandInvoice(c),'band-invoice'));band.append(mk('Pago',!!c.payment_received_at,()=>toggleBandPaid(c),'band-paid'));actions.appendChild(band);if(hasSub(c)){const sub=document.createElement('div');sub.className='td-billing-group';sub.innerHTML='<small>Substituto</small>';sub.append(mk('Fatura recebida',!!c.substitute_invoice_received,()=>toggleSubInvoice(c),'sub-invoice'));sub.append(mk('Pago',!!c.substitute_paid,()=>toggleSubPaid(c),'sub-paid'));actions.appendChild(sub)}}
function refresh(){clearTimeout(timer);timer=setTimeout(()=>{const cards=[...document.querySelectorAll('#concerts>.item')];cards.forEach((card,i)=>{const id=card.dataset.concertId||card.querySelector('[data-concert-view]')?.dataset.concertView;const c=id?byId(id):rows()[i];decorateCard(card,c)});window.TeamDuckCompactAgenda?.refresh?.();setTimeout(()=>{[...document.querySelectorAll('#concerts>.item')].forEach((card,i)=>{const id=card.dataset.concertId||card.querySelector('[data-concert-view]')?.dataset.concertView;const c=id?byId(id):rows()[i];if(c)decorateSummary(card,c)})},80)},60)}
function style(){if(q('tdBillingStyle'))return;const s=document.createElement('style');s.id='tdBillingStyle';s.textContent='.td-billing-group{display:flex;align-items:center;gap:6px;flex-wrap:wrap;padding:6px 8px;border:1px solid rgba(255,255,255,.10);border-radius:12px;background:rgba(255,255,255,.025)}.td-billing-group>small{font-size:10px;font-weight:900;letter-spacing:.08em;text-transform:uppercase;opacity:.65;margin-right:2px}.td-billing-btn.td-billing-done{background:#6f7472!important;border-color:#8a8f8d!important;color:#e6e8e7!important;filter:saturate(.1)}.td-compact-summary{position:relative}.td-agenda-billing{grid-column:1/-1;display:flex;gap:7px;flex-wrap:wrap;align-items:center;margin-top:2px;padding-top:8px;border-top:1px solid rgba(255,255,255,.08)}.td-agenda-billing-row{display:flex;align-items:center;gap:5px}.td-agenda-billing-row>small{font-size:9px;font-weight:900;letter-spacing:.08em;text-transform:uppercase;opacity:.58}.td-agenda-billing-chip{appearance:none;border:1px solid rgba(255,255,255,.24)!important;background:rgba(8,18,13,.62)!important;color:#eef3ef!important;border-radius:999px!important;padding:5px 8px!important;min-width:0!important;font-size:10px!important;line-height:1!important;font-weight:900!important;box-shadow:none!important;white-space:nowrap}.td-agenda-billing-chip.td-done{background:#6f7472!important;border-color:#8f9492!important;color:#f2f3f2!important;filter:saturate(.05)}#concerts>.item.td-past-date .td-agenda-billing-chip:not(.td-done){filter:none!important;color:#f5f7f6!important;border-color:rgba(255,255,255,.28)!important}.td-compact-summary:has(.td-agenda-billing){padding-bottom:10px!important}@media(max-width:600px){.td-agenda-billing{gap:5px;padding-top:7px}.td-agenda-billing-row{gap:4px}.td-agenda-billing-chip{font-size:9px!important;padding:5px 7px!important}.td-agenda-billing-row>small{font-size:8px}}';document.head.appendChild(s)}
function boot(){style();refresh();if(typeof window.loadAll==='function'&&!window.__subBillingLoadPatched){const old=window.loadAll;window.loadAll=async function(...args){const r=await old.apply(this,args);refresh();return r};window.__subBillingLoadPatched=true}document.querySelectorAll('#nav button[data-page="agenda"]').forEach(b=>b.addEventListener('click',refresh))}
if(document.readyState==='loading')addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.TeamDuckSubstituteBilling={refresh};
})();